<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="NJsonSchema.Annotations" />
        <ProjectReference Include="..\Nocturne.Core.Constants\Nocturne.Core.Constants.csproj" />
    </ItemGroup>
    <ItemGroup>
        <InternalsVisibleTo Include="Nocturne.Core.Models.Tests" />
    </ItemGroup>
</Project>
