import { svelteConfig, RAW_COLOR_ALLOW } from "@nocturne/eslint-config";

import noImperativeRemoteQuery from "./tools/eslint/no-imperative-remote-query.js";

// Width stays layout the caller owns; height comes only from a control's size.
const HEIGHT_CLASSES = ["h-*", "size-*", "min-h-*", "max-h-*"];
const CONTROL_HEIGHT_HINT =
  "\"{{className}}\" is not allowed on <{{component}}>: its height comes from size. Use size=\"xs\" (h-7), \"sm\" (h-8) or the default (h-9); each matches the same size on Button, Input, SelectTrigger and Toggle.";

export default [
  ...svelteConfig({
    componentDirs: ["src/lib/components/ui/**"],
    // Generated by the API build; gitignored, so linting it makes counts depend on whether it was built.
    ignores: ["src/lib/api/generated/**", "src/lib/api/api-client.generated.ts"],
    // First-run setup draws its step list and path cards in its own --onb-* palette (see
    // its raw-colour exemption below), which no <Button> variant carries.
    rawButtonFiles: ["src/routes/(unauthenticated)/setup/**/*.svelte"],
    noRestyle: {
      allow: ["layout"],
      // A later matching contract replaces an earlier one, so each restates layout.
      contracts: [
        // A rule between sections is the caller's: CardHeader and CardFooter pad a
        // border-b or border-t they are given. Tabs, its panels and the sidebar's
        // regions draw nothing, and a sheet does not pad its body.
        {
          pattern: "^Card(Header|Content|Footer)$|^(Dialog|Sheet|AlertDialog)(Header|Footer)$|^(Popover|Collapsible)Content$|^Tabs(Content)?$|^Sidebar(Header|Footer|MenuItem)$|^SheetContent$",
          allow: ["layout", "spacing", "border-t", "border-b"]
        },
        {
          pattern: "^Table(Cell|Head)$",
          // A column's width is the caller's; truncate keeps its content inside it.
          allow: ["layout", "spacing", "tabular-nums", "font-mono", "font-medium", "truncate"],
          message: { color: 'Use <{{component}} variant="muted"> for a secondary column or an empty-table message.' }
        },
        // A slug or other identifier keeps its figures aligned.
        { pattern: "^(Card|Alert|AlertDialog)Description$", allow: ["layout", "gap", "font-mono"] },
        // These draw nothing and lay out the caller's own children, whose spacing they cannot know.
        { pattern: "^(Collapsible|Popover|Tooltip)Trigger$|^RadioGroup(\\.Root)?$", allow: ["layout", "gap"] },
        // Initials scale with the avatar, whose size the caller sets.
        { pattern: "^AvatarFallback$", allow: ["layout", "text-xs", "text-sm", "text-base", "text-lg", "text-xl"] },
        { pattern: "^(Card|Dialog|Sheet|AlertDialog)Title$", allow: ["layout", "typography", "gap"] },
        {
          pattern: "^(Input|SelectTrigger)$",
          allow: ["layout", "tabular-nums", "font-mono"],
          deny: HEIGHT_CLASSES,
          message: {
            layout: CONTROL_HEIGHT_HINT,
            spacing: 'Use size="xs" or "sm" on <{{component}}>; each matches the same size on Input, SelectTrigger and ToggleGroup. For an icon or text inside the field, use <InputGroup.Root> with an <InputGroup.Addon> and <InputGroup.Input>.',
            typography: 'Use size="xs" or "sm" on <{{component}}>; Input also has variant="code" for device codes.',
            color: "Mark an invalid field with aria-invalid, which <{{component}}> already styles. On <Input>, mark a value the server accepted (e.g. an available username) with valid."
          }
        },
        {
          pattern: "^InputGroup(\\.Input|Input)$",
          allow: ["layout", "tabular-nums", "font-mono"],
          deny: HEIGHT_CLASSES,
          message: "<InputGroup.Root> owns the field's border, height and padding; put icons and text in <InputGroup.Addon> (align=\"inline-start\" or \"inline-end\")."
        },
        {
          pattern: "^Select(\\.Item|Item)$",
          allow: ["layout"],
          message: {
            typography: 'Set size="xs" on <SelectContent> to match a size="xs" trigger; its items follow.'
          }
        },
        { pattern: "^Textarea$", allow: ["layout", "font-mono"] },
        {
          pattern: "^Label$",
          allow: ["layout"],
          message: {
            typography: 'Use <Label size="sm"> or size="lg", or variant="option" for a checkbox, radio or switch choice.',
            color: 'Use <Label variant="muted"> for a secondary caption.'
          }
        },
        {
          pattern: "^ToggleGroup(Item)?$",
          allow: ["layout"],
          deny: HEIGHT_CLASSES,
          message: 'Set it on <ToggleGroup>: size="xs" (h-7) or "sm" (h-8) for a compact row, variant="segmented" for a view switcher, spacing={1} for separate chips.'
        },
        {
          pattern: "^Toggle$",
          allow: ["layout"],
          deny: HEIGHT_CLASSES,
          message: { layout: CONTROL_HEIGHT_HINT }
        },
        // A placeholder takes the radius of the content it stands in for.
        { pattern: "^Skeleton$", allow: ["layout", "rounded"] },
        {
          pattern: "^Button$",
          allow: ["layout"],
          deny: HEIGHT_CLASSES,
          message: {
            color: "\"{{className}}\" is not allowed on <Button>: pick a variant: subtle for muted text with no fill (a disclosure toggle), ghost-muted for a quiet action, overlay over a full-screen display such as a clock face. For a colour the theme does not own (an OIDC provider's brand), use variant=\"brand\" and pass brand with its background and foreground, the foreground picked for contrast by the API.",
            layout: "\"{{className}}\" is not allowed on <Button>: its height comes from size. Use xs (h-7), sm (h-8), default (h-9), lg (h-10), xl (h-14, full-screen alarm actions), icon-xs (size-7), icon-sm (size-8), icon (size-9), icon-2xs (size-5, a round remove pip), or inline (h-auto, no padding) for a link in running text, inline-xs beside text-xs copy. Width stays yours.",
            typography: "\"{{className}}\" is not allowed on <Button>: it owns its type. size=\"xs\" and \"inline-xs\" give text-xs and size=\"xl\" text-lg; every other size is text-sm font-medium. A combobox or date-picker trigger is variant=\"combobox\".",
            effects: "\"{{className}}\" is not allowed on <Button>: it owns its effects. For a remove that shows on hover, set reveal: it stays hidden until its `group` is hovered or holds focus."
          }
        },
        {
          pattern: "^(Badge|Alert|Card)(\\.Root)?$",
          allow: ["layout"]
        },
        // An identifier or a count keeps its figures aligned.
        { pattern: "^Badge$", allow: ["layout", "font-mono", "tabular-nums"] },
        {
          pattern: "^(Item|RadioGroup\\.Card|RadioGroupCard)$",
          allow: ["layout"],
          message: {
            color: 'Use <Item variant="outline">, "success", "destructive", "demo", "muted", "dashed" or "ghost". aria-current="true" marks the current item, aria-busy a running one, and disabled dims it. <RadioGroup.Card> styles its own checked state.',
            spacing: 'Use <Item size="sm">, the default or size="lg".'
          }
        },
        {
          pattern: "^Banner$",
          allow: ["layout"],
          message: {
            color: 'Use <Banner variant="warning"> or variant="info"; the tints are opaque so content scrolled beneath does not show through.'
          }
        }
      ]
    }
  }),
  {
    // Where notification and tracker urgency is drawn, the nearest-token hint would
    // offer an unrelated red or amber; the ramp is its own token family.
    files: [
      "src/lib/components/trackers/**",
      "src/lib/components/layout/{NotificationItem,SidebarNotifications}.svelte",
      "src/lib/components/status-pills/TrackerPill.svelte",
      "src/lib/components/calendar/{CalendarDayCell,TrackerPopoverContent}.svelte",
      "src/lib/components/dashboard/widgets/TrackersWidget.svelte",
      "src/routes/(authenticated)/notifications/**"
    ],
    rules: {
      "shadcn/no-raw-colors": ["error", {
        allow: RAW_COLOR_ALLOW,
        message: "\"{{className}}\" is a raw colour. For urgency use the severity tokens, which order urgent > hazard > warn > info (text-severity-hazard, bg-severity-warn/10, border-severity-info/20), or <Badge variant=\"severity-hazard\"> for a solid chip; anything else takes a theme token from {{file}}."
      }]
    }
  },
  {
    // Clock faces render styles their owner authored in the clock builder: colours,
    // sizes, positions and free-form custom CSS.
    files: [
      "src/lib/components/clock/**",
      "src/lib/components/clock-builder/**",
      "src/routes/(authenticated)/clock/**"
    ],
    rules: {
      "shadcn/no-inline-styles": "off"
    }
  },
  {
    // First-run setup is its own visual language: a fixed navy backdrop in its own --onb-*
    // palette. Its header draws the brand mark in the brand's colours.
    files: ["src/routes/(unauthenticated)/setup/+page@.svelte"],
    rules: {
      "shadcn/no-raw-colors": "off"
    }
  },
  {
    // Theme cards preview the palettes of themes that are not active, which the
    // active theme's tokens cannot express.
    files: ["src/routes/(authenticated)/settings/appearance/+page.svelte"],
    rules: {
      "shadcn/no-inline-styles": ["error", { allow: ["background"] }]
    }
  },
  {
    // Guard against the year-overview/alerts-polling regression class: a remote
    // query() awaited or `.then()`-chained imperatively (outside a reactive
    // context) throws "not created in a reactive context ... Use .run()".
    files: ["**/*.svelte", "**/*.svelte.ts"],
    plugins: {
      nocturne: {
        rules: { "no-imperative-remote-query": noImperativeRemoteQuery }
      }
    },
    rules: {
      "nocturne/no-imperative-remote-query": "error"
    }
  }
];
