// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nocturne.Infrastructure.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Nocturne.Infrastructure.Data.Migrations
{
    [DbContext(typeof(NocturneDbContext))]
    [Migration("20250727053615_AddDiscrepancyAnalysisTables")]
    partial class AddDiscrepancyAnalysisTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Nocturne.Infrastructure.Data.Entities.DeviceStatusEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CgmJson")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("null")
                        .HasColumnName("cgm");

                    b.Property<string>("ConnectJson")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("null")
                        .HasColumnName("connect");

                    b.Property<string>("CreatedAt")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("created_at");

                    b.Property<string>("Device")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("device");

                    b.Property<string>("InsulinPenJson")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("null")
                        .HasColumnName("insulinPen");

                    b.Property<bool?>("IsCharging")
                        .HasColumnType("boolean")
                        .HasColumnName("isCharging");

                    b.Property<string>("LoopJson")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("null")
                        .HasColumnName("loop");

                    b.Property<string>("MeterJson")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("null")
                        .HasColumnName("meter");

                    b.Property<long>("Mills")
                        .HasColumnType("bigint")
                        .HasColumnName("mills");

                    b.Property<string>("OpenApsJson")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("null")
                        .HasColumnName("openaps");

                    b.Property<string>("OriginalId")
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("original_id");

                    b.Property<string>("OverrideJson")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("null")
                        .HasColumnName("override");

                    b.Property<string>("PumpJson")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("null")
                        .HasColumnName("pump");

                    b.Property<string>("RadioAdapterJson")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("null")
                        .HasColumnName("radioAdapter");

                    b.Property<DateTime>("SysCreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sys_created_at");

                    b.Property<DateTime>("SysUpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sys_updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("UploaderJson")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("null")
                        .HasColumnName("uploader");

                    b.Property<int?>("UtcOffset")
                        .HasColumnType("integer")
                        .HasColumnName("utcOffset");

                    b.Property<string>("XDripJsJson")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("null")
                        .HasColumnName("xdripjs");

                    b.HasKey("Id");

                    b.HasIndex("Device")
                        .HasDatabaseName("ix_devicestatus_device");

                    b.HasIndex("Mills")
                        .IsDescending()
                        .HasDatabaseName("ix_devicestatus_mills");

                    b.HasIndex("SysCreatedAt")
                        .HasDatabaseName("ix_devicestatus_sys_created_at");

                    b.HasIndex("Device", "Mills")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_devicestatus_device_mills");

                    b.ToTable("devicestatus");
                });

            modelBuilder.Entity("Nocturne.Infrastructure.Data.Entities.DiscrepancyAnalysisEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AnalysisTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("analysis_timestamp");

                    b.Property<bool>("BodyMatch")
                        .HasColumnType("boolean")
                        .HasColumnName("body_match");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("correlation_id");

                    b.Property<int>("CriticalDiscrepancyCount")
                        .HasColumnType("integer")
                        .HasColumnName("critical_discrepancy_count");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error_message");

                    b.Property<int>("MajorDiscrepancyCount")
                        .HasColumnType("integer")
                        .HasColumnName("major_discrepancy_count");

                    b.Property<int>("MinorDiscrepancyCount")
                        .HasColumnType("integer")
                        .HasColumnName("minor_discrepancy_count");

                    b.Property<bool>("NightscoutMissing")
                        .HasColumnType("boolean")
                        .HasColumnName("nightscout_missing");

                    b.Property<long?>("NightscoutResponseTimeMs")
                        .HasColumnType("bigint")
                        .HasColumnName("nightscout_response_time_ms");

                    b.Property<int?>("NightscoutStatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("nightscout_status_code");

                    b.Property<bool>("NocturneMissing")
                        .HasColumnType("boolean")
                        .HasColumnName("nocturne_missing");

                    b.Property<long?>("NocturneResponseTimeMs")
                        .HasColumnType("bigint")
                        .HasColumnName("nocturne_response_time_ms");

                    b.Property<int?>("NocturneStatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("nocturne_status_code");

                    b.Property<int>("OverallMatch")
                        .HasColumnType("integer")
                        .HasColumnName("overall_match");

                    b.Property<string>("RequestMethod")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("request_method");

                    b.Property<string>("RequestPath")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("request_path");

                    b.Property<string>("SelectedResponseTarget")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("selected_response_target");

                    b.Property<string>("SelectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("selection_reason");

                    b.Property<bool>("StatusCodeMatch")
                        .HasColumnType("boolean")
                        .HasColumnName("status_code_match");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("summary");

                    b.Property<long>("TotalProcessingTimeMs")
                        .HasColumnType("bigint")
                        .HasColumnName("total_processing_time_ms");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisTimestamp")
                        .IsDescending()
                        .HasDatabaseName("ix_discrepancy_analyses_timestamp");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("ix_discrepancy_analyses_correlation_id");

                    b.HasIndex("OverallMatch")
                        .HasDatabaseName("ix_discrepancy_analyses_overall_match");

                    b.HasIndex("RequestPath")
                        .HasDatabaseName("ix_discrepancy_analyses_request_path");

                    b.HasIndex("RequestPath", "AnalysisTimestamp")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_discrepancy_analyses_path_timestamp");

                    b.ToTable("discrepancy_analyses");
                });

            modelBuilder.Entity("Nocturne.Infrastructure.Data.Entities.DiscrepancyDetailEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AnalysisId")
                        .HasColumnType("uuid")
                        .HasColumnName("analysis_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<int>("DiscrepancyType")
                        .HasColumnType("integer")
                        .HasColumnName("discrepancy_type");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("field");

                    b.Property<string>("NightscoutValue")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("nightscout_value");

                    b.Property<string>("NocturneValue")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("nocturne_value");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<int>("Severity")
                        .HasColumnType("integer")
                        .HasColumnName("severity");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisId")
                        .HasDatabaseName("ix_discrepancy_details_analysis_id");

                    b.HasIndex("DiscrepancyType")
                        .HasDatabaseName("ix_discrepancy_details_type");

                    b.HasIndex("Severity")
                        .HasDatabaseName("ix_discrepancy_details_severity");

                    b.ToTable("discrepancy_details");
                });

            modelBuilder.Entity("Nocturne.Infrastructure.Data.Entities.EntryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedAt")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("created_at");

                    b.Property<string>("DateString")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("dateString");

                    b.Property<double?>("Delta")
                        .HasColumnType("double precision")
                        .HasColumnName("delta");

                    b.Property<string>("Device")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("device");

                    b.Property<string>("Direction")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("direction");

                    b.Property<double?>("Filtered")
                        .HasColumnType("double precision")
                        .HasColumnName("filtered");

                    b.Property<double?>("Intercept")
                        .HasColumnType("double precision")
                        .HasColumnName("intercept");

                    b.Property<bool>("IsDemo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_demo");

                    b.Property<string>("MetaJson")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("{}")
                        .HasColumnName("meta");

                    b.Property<double>("Mgdl")
                        .HasColumnType("double precision")
                        .HasColumnName("mgdl");

                    b.Property<long>("Mills")
                        .HasColumnType("bigint")
                        .HasColumnName("mills");

                    b.Property<double?>("Mmol")
                        .HasColumnType("double precision")
                        .HasColumnName("mmol");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<int?>("Noise")
                        .HasColumnType("integer")
                        .HasColumnName("noise");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("OriginalId")
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("original_id");

                    b.Property<int?>("Rssi")
                        .HasColumnType("integer")
                        .HasColumnName("rssi");

                    b.Property<double?>("Scale")
                        .HasColumnType("double precision")
                        .HasColumnName("scale");

                    b.Property<string>("ScaledJson")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("null")
                        .HasColumnName("scaled");

                    b.Property<double?>("Sgv")
                        .HasColumnType("double precision")
                        .HasColumnName("sgv");

                    b.Property<double?>("Slope")
                        .HasColumnType("double precision")
                        .HasColumnName("slope");

                    b.Property<DateTime>("SysCreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sys_created_at");

                    b.Property<string>("SysTime")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("sysTime");

                    b.Property<DateTime>("SysUpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sys_updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Type")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("sgv")
                        .HasColumnName("type");

                    b.Property<double?>("Unfiltered")
                        .HasColumnType("double precision")
                        .HasColumnName("unfiltered");

                    b.Property<int?>("UtcOffset")
                        .HasColumnType("integer")
                        .HasColumnName("utcOffset");

                    b.HasKey("Id");

                    b.HasIndex("Mills")
                        .IsDescending()
                        .HasDatabaseName("ix_entries_mills");

                    b.HasIndex("SysCreatedAt")
                        .HasDatabaseName("ix_entries_sys_created_at");

                    b.HasIndex("Type")
                        .HasDatabaseName("ix_entries_type");

                    b.HasIndex("Type", "Mills")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_entries_type_mills");

                    b.ToTable("entries");
                });

            modelBuilder.Entity("Nocturne.Infrastructure.Data.Entities.FoodEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Carbs")
                        .HasColumnType("double precision")
                        .HasColumnName("carbs");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("category");

                    b.Property<double>("Energy")
                        .HasColumnType("double precision")
                        .HasColumnName("energy");

                    b.Property<double>("Fat")
                        .HasColumnType("double precision")
                        .HasColumnName("fat");

                    b.Property<string>("Foods")
                        .HasColumnType("text")
                        .HasColumnName("foods");

                    b.Property<int>("Gi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(2)
                        .HasColumnName("gi");

                    b.Property<bool>("Hidden")
                        .HasColumnType("boolean")
                        .HasColumnName("hidden");

                    b.Property<bool>("HideAfterUse")
                        .HasColumnType("boolean")
                        .HasColumnName("hide_after_use");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.Property<string>("OriginalId")
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("original_id");

                    b.Property<double>("Portion")
                        .HasColumnType("double precision")
                        .HasColumnName("portion");

                    b.Property<int>("Position")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(99999)
                        .HasColumnName("position");

                    b.Property<double>("Protein")
                        .HasColumnType("double precision")
                        .HasColumnName("protein");

                    b.Property<string>("Subcategory")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("subcategory");

                    b.Property<DateTime>("SysCreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sys_created_at");

                    b.Property<DateTime>("SysUpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sys_updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Type")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("food")
                        .HasColumnName("type");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("g")
                        .HasColumnName("unit");

                    b.HasKey("Id");

                    b.HasIndex("Category")
                        .HasDatabaseName("ix_foods_category");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_foods_name");

                    b.HasIndex("SysCreatedAt")
                        .HasDatabaseName("ix_foods_sys_created_at");

                    b.HasIndex("Type")
                        .HasDatabaseName("ix_foods_type");

                    b.HasIndex("Type", "Name")
                        .HasDatabaseName("ix_foods_type_name");

                    b.ToTable("foods");
                });

            modelBuilder.Entity("Nocturne.Infrastructure.Data.Entities.ProfileEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedAt")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("CreatedAtPg")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_pg")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DefaultProfile")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("Default")
                        .HasColumnName("default_profile");

                    b.Property<long>("Mills")
                        .HasColumnType("bigint")
                        .HasColumnName("mills");

                    b.Property<string>("OriginalId")
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("original_id");

                    b.Property<string>("StartDate")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("start_date");

                    b.Property<string>("StoreJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("{}")
                        .HasColumnName("store_json");

                    b.Property<string>("Units")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("mg/dl")
                        .HasColumnName("units");

                    b.Property<DateTime>("UpdatedAtPg")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_pg")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtPg")
                        .HasDatabaseName("ix_profiles_sys_created_at");

                    b.HasIndex("DefaultProfile")
                        .HasDatabaseName("ix_profiles_default_profile");

                    b.HasIndex("Mills")
                        .IsDescending()
                        .HasDatabaseName("ix_profiles_mills");

                    b.HasIndex("Units")
                        .HasDatabaseName("ix_profiles_units");

                    b.ToTable("profiles");
                });

            modelBuilder.Entity("Nocturne.Infrastructure.Data.Entities.SettingsEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("App")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("app");

                    b.Property<string>("CreatedAt")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("created_at");

                    b.Property<string>("Device")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("device");

                    b.Property<string>("EnteredBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("entered_by");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("key");

                    b.Property<long>("Mills")
                        .HasColumnType("bigint")
                        .HasColumnName("mills");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<string>("OriginalId")
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("original_id");

                    b.Property<DateTimeOffset?>("SrvCreated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("srv_created");

                    b.Property<DateTimeOffset?>("SrvModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("srv_modified");

                    b.Property<DateTime>("SysCreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sys_created_at");

                    b.Property<DateTime>("SysUpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sys_updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("UtcOffset")
                        .HasColumnType("integer")
                        .HasColumnName("utc_offset");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.Property<int?>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_settings_is_active");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("ix_settings_key");

                    b.HasIndex("Mills")
                        .IsDescending()
                        .HasDatabaseName("ix_settings_mills");

                    b.HasIndex("SysCreatedAt")
                        .HasDatabaseName("ix_settings_sys_created_at");

                    b.ToTable("settings");
                });

            modelBuilder.Entity("Nocturne.Infrastructure.Data.Entities.TreatmentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double?>("Absolute")
                        .HasColumnType("double precision")
                        .HasColumnName("absolute");

                    b.Property<int?>("AbsorptionTime")
                        .HasColumnType("integer")
                        .HasColumnName("absorptionTime");

                    b.Property<string>("BolusCalcJson")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("{}")
                        .HasColumnName("boluscalc");

                    b.Property<double?>("CR")
                        .HasColumnType("double precision")
                        .HasColumnName("CR");

                    b.Property<int?>("CarbTime")
                        .HasColumnType("integer")
                        .HasColumnName("carbTime");

                    b.Property<double?>("Carbs")
                        .HasColumnType("double precision")
                        .HasColumnName("carbs");

                    b.Property<bool?>("CircadianPercentageProfile")
                        .HasColumnType("boolean")
                        .HasColumnName("CircadianPercentageProfile");

                    b.Property<string>("Created_at")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("created_at");

                    b.Property<string>("CuttedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("cuttedby");

                    b.Property<string>("Cutting")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("cutting");

                    b.Property<long?>("Date")
                        .HasColumnType("bigint")
                        .HasColumnName("date");

                    b.Property<double?>("Duration")
                        .HasColumnType("double precision")
                        .HasColumnName("duration");

                    b.Property<string>("DurationType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("durationType");

                    b.Property<bool?>("End")
                        .HasColumnType("boolean")
                        .HasColumnName("end");

                    b.Property<long?>("EndMills")
                        .HasColumnType("bigint")
                        .HasColumnName("endmills");

                    b.Property<string>("EndProfile")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("endprofile");

                    b.Property<string>("EnteredBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("enteredBy");

                    b.Property<double?>("EnteredInsulin")
                        .HasColumnType("double precision")
                        .HasColumnName("enteredinsulin");

                    b.Property<string>("EventTime")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("eventTime");

                    b.Property<string>("EventType")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("eventType");

                    b.Property<double?>("Fat")
                        .HasColumnType("double precision")
                        .HasColumnName("fat");

                    b.Property<bool?>("First")
                        .HasColumnType("boolean")
                        .HasColumnName("first");

                    b.Property<string>("FoodType")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("foodType");

                    b.Property<double?>("Glucose")
                        .HasColumnType("double precision")
                        .HasColumnName("glucose");

                    b.Property<string>("GlucoseType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("glucoseType");

                    b.Property<double?>("Insulin")
                        .HasColumnType("double precision")
                        .HasColumnName("insulin");

                    b.Property<double?>("InsulinNeedsScaleFactor")
                        .HasColumnType("double precision")
                        .HasColumnName("insulinNeedsScaleFactor");

                    b.Property<bool?>("IsAnnouncement")
                        .HasColumnType("boolean")
                        .HasColumnName("isAnnouncement");

                    b.Property<double?>("Mgdl")
                        .HasColumnType("double precision")
                        .HasColumnName("mgdl");

                    b.Property<long>("Mills")
                        .HasColumnType("bigint")
                        .HasColumnName("mills");

                    b.Property<double?>("Mmol")
                        .HasColumnType("double precision")
                        .HasColumnName("mmol");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("NsClientId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("NSCLIENT_ID");

                    b.Property<string>("OriginalId")
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("original_id");

                    b.Property<double?>("Percent")
                        .HasColumnType("double precision")
                        .HasColumnName("percent");

                    b.Property<double?>("Percentage")
                        .HasColumnType("double precision")
                        .HasColumnName("percentage");

                    b.Property<double?>("PreBolus")
                        .HasColumnType("double precision")
                        .HasColumnName("preBolus");

                    b.Property<string>("Profile")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("profile");

                    b.Property<string>("ProfileJson")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("null")
                        .HasColumnName("profileJson");

                    b.Property<double?>("Protein")
                        .HasColumnType("double precision")
                        .HasColumnName("protein");

                    b.Property<double?>("Rate")
                        .HasColumnType("double precision")
                        .HasColumnName("rate");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<double?>("Relative")
                        .HasColumnType("double precision")
                        .HasColumnName("relative");

                    b.Property<string>("Source")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("source");

                    b.Property<string>("Split")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("split");

                    b.Property<double?>("SplitExt")
                        .HasColumnType("double precision")
                        .HasColumnName("splitExt");

                    b.Property<double?>("SplitNow")
                        .HasColumnType("double precision")
                        .HasColumnName("splitNow");

                    b.Property<string>("Status")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("status");

                    b.Property<DateTime>("SysCreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sys_created_at");

                    b.Property<DateTime>("SysUpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sys_updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<double?>("TargetBottom")
                        .HasColumnType("double precision")
                        .HasColumnName("targetBottom");

                    b.Property<double?>("TargetTop")
                        .HasColumnType("double precision")
                        .HasColumnName("targetTop");

                    b.Property<double?>("Timeshift")
                        .HasColumnType("double precision")
                        .HasColumnName("timeshift");

                    b.Property<long?>("Timestamp")
                        .HasColumnType("bigint")
                        .HasColumnName("timestamp");

                    b.Property<string>("TransmitterId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("transmitterId");

                    b.Property<string>("Units")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("units");

                    b.Property<int?>("UtcOffset")
                        .HasColumnType("integer")
                        .HasColumnName("utcOffset");

                    b.HasKey("Id");

                    b.HasIndex("EventType")
                        .HasDatabaseName("ix_treatments_event_type");

                    b.HasIndex("Mills")
                        .IsDescending()
                        .HasDatabaseName("ix_treatments_mills");

                    b.HasIndex("SysCreatedAt")
                        .HasDatabaseName("ix_treatments_sys_created_at");

                    b.HasIndex("EventType", "Mills")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_treatments_event_type_mills");

                    b.ToTable("treatments");
                });

            modelBuilder.Entity("Nocturne.Infrastructure.Data.Entities.DiscrepancyDetailEntity", b =>
                {
                    b.HasOne("Nocturne.Infrastructure.Data.Entities.DiscrepancyAnalysisEntity", "Analysis")
                        .WithMany("Discrepancies")
                        .HasForeignKey("AnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Analysis");
                });

            modelBuilder.Entity("Nocturne.Infrastructure.Data.Entities.DiscrepancyAnalysisEntity", b =>
                {
                    b.Navigation("Discrepancies");
                });
#pragma warning restore 612, 618
        }
    }
}
