// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nocturne.Infrastructure.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Nocturne.Infrastructure.Data.Migrations
{
    [DbContext(typeof(NocturneDbContext))]
    [Migration("20250810100525_AddSysTrackingDefaults")]
    partial class AddSysTrackingDefaults
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Nocturne.Infrastructure.Data.Entities.ActivityEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdditionalPropertiesJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("additional_properties");

                    b.Property<string>("CreatedAt")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("created_at");

                    b.Property<string>("DateString")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("dateString");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<double?>("Duration")
                        .HasColumnType("double precision")
                        .HasColumnName("duration");

                    b.Property<string>("EnteredBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("enteredBy");

                    b.Property<string>("Intensity")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("intensity");

                    b.Property<long>("Mills")
                        .HasColumnType("bigint")
                        .HasColumnName("mills");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("OriginalId")
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("original_id");

                    b.Property<DateTime>("SysCreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sys_created_at");

                    b.Property<DateTime>("SysUpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sys_updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long?>("Timestamp")
                        .HasColumnType("bigint")
                        .HasColumnName("timestamp");

                    b.Property<string>("Type")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("type");

                    b.Property<int?>("UtcOffset")
                        .HasColumnType("integer")
                        .HasColumnName("utcOffset");

                    b.HasKey("Id");

                    b.HasIndex("Mills")
                        .IsDescending()
                        .HasDatabaseName("ix_activities_mills");

                    b.HasIndex("SysCreatedAt")
                        .HasDatabaseName("ix_activities_sys_created_at");

                    b.HasIndex("Type")
                        .HasDatabaseName("ix_activities_type");

                    b.HasIndex("Type", "Mills")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_activities_type_mills");

                    b.ToTable("activities");
                });

            modelBuilder.Entity("Nocturne.Infrastructure.Data.Entities.AlertHistoryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AcknowledgedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("acknowledged_at");

                    b.Property<string>("AcknowledgmentNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("acknowledgment_notes");

                    b.Property<Guid?>("AlertRuleId")
                        .HasColumnType("uuid")
                        .HasColumnName("alert_rule_id");

                    b.Property<string>("AlertType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("alert_type");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("EscalationAttempts")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("escalation_attempts");

                    b.Property<int>("EscalationLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("escalation_level");

                    b.Property<bool>("EscalationPaused")
                        .HasColumnType("boolean")
                        .HasColumnName("escalation_paused");

                    b.Property<string>("EscalationReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("escalation_reason");

                    b.Property<decimal?>("GlucoseValue")
                        .HasColumnType("numeric")
                        .HasColumnName("glucose_value");

                    b.Property<DateTime?>("NextEscalationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_escalation_time");

                    b.Property<string>("NotificationsSent")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("[]")
                        .HasColumnName("notifications_sent");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<int>("SnoozeCount")
                        .HasColumnType("integer")
                        .HasColumnName("snooze_count");

                    b.Property<string>("SnoozeReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("snooze_reason");

                    b.Property<DateTime?>("SnoozeUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("snooze_until");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<decimal?>("Threshold")
                        .HasColumnType("numeric")
                        .HasColumnName("threshold");

                    b.Property<DateTime>("TriggerTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("trigger_time");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("AlertRuleId")
                        .HasDatabaseName("ix_alert_history_alert_rule_id");

                    b.HasIndex("AlertType")
                        .HasDatabaseName("ix_alert_history_alert_type");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_alert_history_status");

                    b.HasIndex("TriggerTime")
                        .IsDescending()
                        .HasDatabaseName("ix_alert_history_trigger_time");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_alert_history_user_id");

                    b.HasIndex("UserId", "Status")
                        .HasDatabaseName("ix_alert_history_user_status");

                    b.HasIndex("UserId", "TriggerTime")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_alert_history_user_trigger_time");

                    b.ToTable("alert_history");
                });

            modelBuilder.Entity("Nocturne.Infrastructure.Data.Entities.AlertRuleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActiveHours")
                        .HasColumnType("jsonb")
                        .HasColumnName("active_hours");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DaysOfWeek")
                        .HasColumnType("jsonb")
                        .HasColumnName("days_of_week");

                    b.Property<int>("DefaultSnoozeMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(30)
                        .HasColumnName("default_snooze_minutes");

                    b.Property<int>("EscalationDelayMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(15)
                        .HasColumnName("escalation_delay_minutes");

                    b.Property<decimal?>("HighThreshold")
                        .HasColumnType("numeric")
                        .HasColumnName("high_threshold");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_enabled");

                    b.Property<decimal?>("LowThreshold")
                        .HasColumnType("numeric")
                        .HasColumnName("low_threshold");

                    b.Property<int>("MaxEscalations")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(3)
                        .HasColumnName("max_escalations");

                    b.Property<int>("MaxSnoozeMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(120)
                        .HasColumnName("max_snooze_minutes");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("NotificationChannels")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("[]")
                        .HasColumnName("notification_channels");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal?>("UrgentHighThreshold")
                        .HasColumnType("numeric")
                        .HasColumnName("urgent_high_threshold");

                    b.Property<decimal?>("UrgentLowThreshold")
                        .HasColumnType("numeric")
                        .HasColumnName("urgent_low_threshold");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_alert_rules_created_at");

                    b.HasIndex("IsEnabled")
                        .HasDatabaseName("ix_alert_rules_is_enabled");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_alert_rules_user_id");

                    b.HasIndex("UserId", "IsEnabled")
                        .HasDatabaseName("ix_alert_rules_user_enabled");

                    b.ToTable("alert_rules");
                });

            modelBuilder.Entity("Nocturne.Infrastructure.Data.Entities.DeviceHealthEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("BatteryLevel")
                        .HasColumnType("numeric")
                        .HasColumnName("battery_level");

                    b.Property<decimal>("BatteryWarningThreshold")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric")
                        .HasDefaultValue(20.0m)
                        .HasColumnName("battery_warning_threshold");

                    b.Property<int>("CalibrationReminderHours")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(12)
                        .HasColumnName("calibration_reminder_hours");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("DataGapWarningMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(30)
                        .HasColumnName("data_gap_warning_minutes");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("device_id");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("device_name");

                    b.Property<int>("DeviceType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(3)
                        .HasColumnName("device_type");

                    b.Property<DateTime?>("LastCalibration")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_calibration");

                    b.Property<DateTime?>("LastDataReceived")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_data_received");

                    b.Property<string>("LastErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("last_error_message");

                    b.Property<DateTime?>("LastMaintenanceAlert")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_maintenance_alert");

                    b.Property<DateTime?>("LastStatusUpdate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_status_update");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("manufacturer");

                    b.Property<string>("Model")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("model");

                    b.Property<DateTime?>("SensorExpiration")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sensor_expiration");

                    b.Property<int>("SensorExpirationWarningHours")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(24)
                        .HasColumnName("sensor_expiration_warning_hours");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("serial_number");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_device_health_created_at");

                    b.HasIndex("DeviceId")
                        .IsUnique()
                        .HasDatabaseName("ix_device_health_device_id");

                    b.HasIndex("DeviceType")
                        .HasDatabaseName("ix_device_health_device_type");

                    b.HasIndex("LastDataReceived")
                        .IsDescending()
                        .HasDatabaseName("ix_device_health_last_data_received");

                    b.HasIndex("LastMaintenanceAlert")
                        .HasDatabaseName("ix_device_health_last_maintenance_alert");

                    b.HasIndex("SensorExpiration")
                        .HasDatabaseName("ix_device_health_sensor_expiration");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_device_health_status");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_device_health_user_id");

                    b.HasIndex("UserId", "DeviceType")
                        .HasDatabaseName("ix_device_health_user_device_type");

                    b.HasIndex("UserId", "Status")
                        .HasDatabaseName("ix_device_health_user_status");

                    b.ToTable("device_health");
                });

            modelBuilder.Entity("Nocturne.Infrastructure.Data.Entities.DeviceStatusEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdditionalPropertiesJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("additional_properties");

                    b.Property<string>("CgmJson")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("null")
                        .HasColumnName("cgm");

                    b.Property<string>("ConnectJson")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("null")
                        .HasColumnName("connect");

                    b.Property<string>("CreatedAt")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("created_at");

                    b.Property<string>("Device")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("device");

                    b.Property<string>("InsulinPenJson")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("null")
                        .HasColumnName("insulinPen");

                    b.Property<bool?>("IsCharging")
                        .HasColumnType("boolean")
                        .HasColumnName("isCharging");

                    b.Property<string>("LoopJson")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("null")
                        .HasColumnName("loop");

                    b.Property<string>("MeterJson")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("null")
                        .HasColumnName("meter");

                    b.Property<long>("Mills")
                        .HasColumnType("bigint")
                        .HasColumnName("mills");

                    b.Property<string>("OpenApsJson")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("null")
                        .HasColumnName("openaps");

                    b.Property<string>("OriginalId")
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("original_id");

                    b.Property<string>("OverrideJson")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("null")
                        .HasColumnName("override");

                    b.Property<string>("PumpJson")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("null")
                        .HasColumnName("pump");

                    b.Property<string>("RadioAdapterJson")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("null")
                        .HasColumnName("radioAdapter");

                    b.Property<DateTime>("SysCreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sys_created_at");

                    b.Property<DateTime>("SysUpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sys_updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("UploaderJson")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("null")
                        .HasColumnName("uploader");

                    b.Property<int?>("UtcOffset")
                        .HasColumnType("integer")
                        .HasColumnName("utcOffset");

                    b.Property<string>("XDripJsJson")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("null")
                        .HasColumnName("xdripjs");

                    b.HasKey("Id");

                    b.HasIndex("Device")
                        .HasDatabaseName("ix_devicestatus_device");

                    b.HasIndex("Mills")
                        .IsDescending()
                        .HasDatabaseName("ix_devicestatus_mills");

                    b.HasIndex("SysCreatedAt")
                        .HasDatabaseName("ix_devicestatus_sys_created_at");

                    b.HasIndex("Device", "Mills")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_devicestatus_device_mills");

                    b.ToTable("devicestatus");
                });

            modelBuilder.Entity("Nocturne.Infrastructure.Data.Entities.DiscrepancyAnalysisEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AnalysisTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("analysis_timestamp");

                    b.Property<bool>("BodyMatch")
                        .HasColumnType("boolean")
                        .HasColumnName("body_match");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("correlation_id");

                    b.Property<int>("CriticalDiscrepancyCount")
                        .HasColumnType("integer")
                        .HasColumnName("critical_discrepancy_count");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error_message");

                    b.Property<int>("MajorDiscrepancyCount")
                        .HasColumnType("integer")
                        .HasColumnName("major_discrepancy_count");

                    b.Property<int>("MinorDiscrepancyCount")
                        .HasColumnType("integer")
                        .HasColumnName("minor_discrepancy_count");

                    b.Property<bool>("NightscoutMissing")
                        .HasColumnType("boolean")
                        .HasColumnName("nightscout_missing");

                    b.Property<long?>("NightscoutResponseTimeMs")
                        .HasColumnType("bigint")
                        .HasColumnName("nightscout_response_time_ms");

                    b.Property<int?>("NightscoutStatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("nightscout_status_code");

                    b.Property<bool>("NocturneMissing")
                        .HasColumnType("boolean")
                        .HasColumnName("nocturne_missing");

                    b.Property<long?>("NocturneResponseTimeMs")
                        .HasColumnType("bigint")
                        .HasColumnName("nocturne_response_time_ms");

                    b.Property<int?>("NocturneStatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("nocturne_status_code");

                    b.Property<int>("OverallMatch")
                        .HasColumnType("integer")
                        .HasColumnName("overall_match");

                    b.Property<string>("RequestMethod")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("request_method");

                    b.Property<string>("RequestPath")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("request_path");

                    b.Property<string>("SelectedResponseTarget")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("selected_response_target");

                    b.Property<string>("SelectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("selection_reason");

                    b.Property<bool>("StatusCodeMatch")
                        .HasColumnType("boolean")
                        .HasColumnName("status_code_match");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("summary");

                    b.Property<long>("TotalProcessingTimeMs")
                        .HasColumnType("bigint")
                        .HasColumnName("total_processing_time_ms");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisTimestamp")
                        .IsDescending()
                        .HasDatabaseName("ix_discrepancy_analyses_timestamp");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("ix_discrepancy_analyses_correlation_id");

                    b.HasIndex("OverallMatch")
                        .HasDatabaseName("ix_discrepancy_analyses_overall_match");

                    b.HasIndex("RequestPath")
                        .HasDatabaseName("ix_discrepancy_analyses_request_path");

                    b.HasIndex("RequestPath", "AnalysisTimestamp")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_discrepancy_analyses_path_timestamp");

                    b.ToTable("discrepancy_analyses");
                });

            modelBuilder.Entity("Nocturne.Infrastructure.Data.Entities.DiscrepancyDetailEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AnalysisId")
                        .HasColumnType("uuid")
                        .HasColumnName("analysis_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<int>("DiscrepancyType")
                        .HasColumnType("integer")
                        .HasColumnName("discrepancy_type");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("field");

                    b.Property<string>("NightscoutValue")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("nightscout_value");

                    b.Property<string>("NocturneValue")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("nocturne_value");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<int>("Severity")
                        .HasColumnType("integer")
                        .HasColumnName("severity");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisId")
                        .HasDatabaseName("ix_discrepancy_details_analysis_id");

                    b.HasIndex("DiscrepancyType")
                        .HasDatabaseName("ix_discrepancy_details_type");

                    b.HasIndex("Severity")
                        .HasDatabaseName("ix_discrepancy_details_severity");

                    b.ToTable("discrepancy_details");
                });

            modelBuilder.Entity("Nocturne.Infrastructure.Data.Entities.EmergencyContactEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AlertTypes")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("[]")
                        .HasColumnName("alert_types");

                    b.Property<int>("ContactType")
                        .HasColumnType("integer")
                        .HasColumnName("contact_type");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("EmailAddress")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email_address");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("phone_number");

                    b.Property<int>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("priority");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ContactType")
                        .HasDatabaseName("ix_emergency_contacts_contact_type");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_emergency_contacts_is_active");

                    b.HasIndex("Priority")
                        .HasDatabaseName("ix_emergency_contacts_priority");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_emergency_contacts_user_id");

                    b.ToTable("emergency_contacts");
                });

            modelBuilder.Entity("Nocturne.Infrastructure.Data.Entities.EntryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdditionalPropertiesJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("additional_properties");

                    b.Property<string>("CreatedAt")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("created_at");

                    b.Property<string>("DateString")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("dateString");

                    b.Property<double?>("Delta")
                        .HasColumnType("double precision")
                        .HasColumnName("delta");

                    b.Property<string>("Device")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("device");

                    b.Property<string>("Direction")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("direction");

                    b.Property<double?>("Filtered")
                        .HasColumnType("double precision")
                        .HasColumnName("filtered");

                    b.Property<double?>("Intercept")
                        .HasColumnType("double precision")
                        .HasColumnName("intercept");

                    b.Property<bool>("IsDemo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_demo");

                    b.Property<string>("MetaJson")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("{}")
                        .HasColumnName("meta");

                    b.Property<double>("Mgdl")
                        .HasColumnType("double precision")
                        .HasColumnName("mgdl");

                    b.Property<long>("Mills")
                        .HasColumnType("bigint")
                        .HasColumnName("mills");

                    b.Property<double?>("Mmol")
                        .HasColumnType("double precision")
                        .HasColumnName("mmol");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<int?>("Noise")
                        .HasColumnType("integer")
                        .HasColumnName("noise");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("OriginalId")
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("original_id");

                    b.Property<int?>("Rssi")
                        .HasColumnType("integer")
                        .HasColumnName("rssi");

                    b.Property<double?>("Scale")
                        .HasColumnType("double precision")
                        .HasColumnName("scale");

                    b.Property<string>("ScaledJson")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("null")
                        .HasColumnName("scaled");

                    b.Property<double?>("Sgv")
                        .HasColumnType("double precision")
                        .HasColumnName("sgv");

                    b.Property<double?>("Slope")
                        .HasColumnType("double precision")
                        .HasColumnName("slope");

                    b.Property<DateTime>("SysCreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sys_created_at");

                    b.Property<string>("SysTime")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("sysTime");

                    b.Property<DateTime>("SysUpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sys_updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Type")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("sgv")
                        .HasColumnName("type");

                    b.Property<double?>("Unfiltered")
                        .HasColumnType("double precision")
                        .HasColumnName("unfiltered");

                    b.Property<int?>("UtcOffset")
                        .HasColumnType("integer")
                        .HasColumnName("utcOffset");

                    b.HasKey("Id");

                    b.HasIndex("Mills")
                        .IsDescending()
                        .HasDatabaseName("ix_entries_mills");

                    b.HasIndex("SysCreatedAt")
                        .HasDatabaseName("ix_entries_sys_created_at");

                    b.HasIndex("Type")
                        .HasDatabaseName("ix_entries_type");

                    b.HasIndex("Type", "Mills")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_entries_type_mills");

                    b.ToTable("entries");
                });

            modelBuilder.Entity("Nocturne.Infrastructure.Data.Entities.FoodEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdditionalPropertiesJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("additional_properties");

                    b.Property<double>("Carbs")
                        .HasColumnType("double precision")
                        .HasColumnName("carbs");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("category");

                    b.Property<double>("Energy")
                        .HasColumnType("double precision")
                        .HasColumnName("energy");

                    b.Property<double>("Fat")
                        .HasColumnType("double precision")
                        .HasColumnName("fat");

                    b.Property<string>("Foods")
                        .HasColumnType("text")
                        .HasColumnName("foods");

                    b.Property<int>("Gi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(2)
                        .HasColumnName("gi");

                    b.Property<bool>("Hidden")
                        .HasColumnType("boolean")
                        .HasColumnName("hidden");

                    b.Property<bool>("HideAfterUse")
                        .HasColumnType("boolean")
                        .HasColumnName("hide_after_use");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.Property<string>("OriginalId")
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("original_id");

                    b.Property<double>("Portion")
                        .HasColumnType("double precision")
                        .HasColumnName("portion");

                    b.Property<int>("Position")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(99999)
                        .HasColumnName("position");

                    b.Property<double>("Protein")
                        .HasColumnType("double precision")
                        .HasColumnName("protein");

                    b.Property<string>("Subcategory")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("subcategory");

                    b.Property<DateTime>("SysCreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sys_created_at");

                    b.Property<DateTime>("SysUpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sys_updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Type")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("food")
                        .HasColumnName("type");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("g")
                        .HasColumnName("unit");

                    b.HasKey("Id");

                    b.HasIndex("Category")
                        .HasDatabaseName("ix_foods_category");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_foods_name");

                    b.HasIndex("SysCreatedAt")
                        .HasDatabaseName("ix_foods_sys_created_at");

                    b.HasIndex("Type")
                        .HasDatabaseName("ix_foods_type");

                    b.HasIndex("Type", "Name")
                        .HasDatabaseName("ix_foods_type_name");

                    b.ToTable("foods");
                });

            modelBuilder.Entity("Nocturne.Infrastructure.Data.Entities.NotificationPreferencesEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("EmailAddress")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email_address");

                    b.Property<bool>("EmailEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("email_enabled");

                    b.Property<bool>("EmergencyOverrideQuietHours")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("emergency_override_quiet_hours");

                    b.Property<string>("PushoverDevices")
                        .HasColumnType("jsonb")
                        .HasColumnName("pushover_devices");

                    b.Property<bool>("PushoverEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("pushover_enabled");

                    b.Property<string>("PushoverUserKey")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("pushover_user_key");

                    b.Property<bool>("QuietHoursEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("quiet_hours_enabled");

                    b.Property<TimeOnly?>("QuietHoursEnd")
                        .HasColumnType("time without time zone")
                        .HasColumnName("quiet_hours_end");

                    b.Property<TimeOnly?>("QuietHoursStart")
                        .HasColumnType("time without time zone")
                        .HasColumnName("quiet_hours_start");

                    b.Property<bool>("SmsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("sms_enabled");

                    b.Property<string>("SmsPhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("sms_phone_number");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("user_id");

                    b.Property<bool>("WebhookEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("webhook_enabled");

                    b.Property<string>("WebhookUrls")
                        .HasColumnType("jsonb")
                        .HasColumnName("webhook_urls");

                    b.HasKey("Id");

                    b.HasIndex("EmailEnabled")
                        .HasDatabaseName("ix_notification_preferences_email_enabled");

                    b.HasIndex("PushoverEnabled")
                        .HasDatabaseName("ix_notification_preferences_pushover_enabled");

                    b.HasIndex("SmsEnabled")
                        .HasDatabaseName("ix_notification_preferences_sms_enabled");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_notification_preferences_user_id");

                    b.ToTable("notification_preferences");
                });

            modelBuilder.Entity("Nocturne.Infrastructure.Data.Entities.ProfileEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdditionalPropertiesJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("additional_properties");

                    b.Property<string>("CreatedAt")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("CreatedAtPg")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_pg")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DefaultProfile")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("Default")
                        .HasColumnName("default_profile");

                    b.Property<long>("Mills")
                        .HasColumnType("bigint")
                        .HasColumnName("mills");

                    b.Property<string>("OriginalId")
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("original_id");

                    b.Property<string>("StartDate")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("start_date");

                    b.Property<string>("StoreJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("{}")
                        .HasColumnName("store_json");

                    b.Property<string>("Units")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("mg/dl")
                        .HasColumnName("units");

                    b.Property<DateTime>("UpdatedAtPg")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_pg")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtPg")
                        .HasDatabaseName("ix_profiles_sys_created_at");

                    b.HasIndex("DefaultProfile")
                        .HasDatabaseName("ix_profiles_default_profile");

                    b.HasIndex("Mills")
                        .IsDescending()
                        .HasDatabaseName("ix_profiles_mills");

                    b.HasIndex("Units")
                        .HasDatabaseName("ix_profiles_units");

                    b.ToTable("profiles");
                });

            modelBuilder.Entity("Nocturne.Infrastructure.Data.Entities.SettingsEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdditionalPropertiesJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("additional_properties");

                    b.Property<string>("App")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("app");

                    b.Property<string>("CreatedAt")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("created_at");

                    b.Property<string>("Device")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("device");

                    b.Property<string>("EnteredBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("entered_by");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("key");

                    b.Property<long>("Mills")
                        .HasColumnType("bigint")
                        .HasColumnName("mills");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<string>("OriginalId")
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("original_id");

                    b.Property<DateTimeOffset?>("SrvCreated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("srv_created");

                    b.Property<DateTimeOffset?>("SrvModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("srv_modified");

                    b.Property<DateTime>("SysCreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sys_created_at");

                    b.Property<DateTime>("SysUpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sys_updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("UtcOffset")
                        .HasColumnType("integer")
                        .HasColumnName("utc_offset");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.Property<int?>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_settings_is_active");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("ix_settings_key");

                    b.HasIndex("Mills")
                        .IsDescending()
                        .HasDatabaseName("ix_settings_mills");

                    b.HasIndex("SysCreatedAt")
                        .HasDatabaseName("ix_settings_sys_created_at");

                    b.ToTable("settings");
                });

            modelBuilder.Entity("Nocturne.Infrastructure.Data.Entities.TreatmentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double?>("Absolute")
                        .HasColumnType("double precision")
                        .HasColumnName("absolute");

                    b.Property<int?>("AbsorptionTime")
                        .HasColumnType("integer")
                        .HasColumnName("absorptionTime");

                    b.Property<string>("AdditionalPropertiesJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("additional_properties");

                    b.Property<string>("BolusCalcJson")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("{}")
                        .HasColumnName("boluscalc");

                    b.Property<double?>("CR")
                        .HasColumnType("double precision")
                        .HasColumnName("CR");

                    b.Property<int?>("CarbTime")
                        .HasColumnType("integer")
                        .HasColumnName("carbTime");

                    b.Property<double?>("Carbs")
                        .HasColumnType("double precision")
                        .HasColumnName("carbs");

                    b.Property<bool?>("CircadianPercentageProfile")
                        .HasColumnType("boolean")
                        .HasColumnName("CircadianPercentageProfile");

                    b.Property<string>("Created_at")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("created_at");

                    b.Property<string>("CuttedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("cuttedby");

                    b.Property<string>("Cutting")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("cutting");

                    b.Property<long?>("Date")
                        .HasColumnType("bigint")
                        .HasColumnName("date");

                    b.Property<double?>("Duration")
                        .HasColumnType("double precision")
                        .HasColumnName("duration");

                    b.Property<string>("DurationType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("durationType");

                    b.Property<bool?>("End")
                        .HasColumnType("boolean")
                        .HasColumnName("end");

                    b.Property<long?>("EndMills")
                        .HasColumnType("bigint")
                        .HasColumnName("endmills");

                    b.Property<string>("EndProfile")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("endprofile");

                    b.Property<string>("EnteredBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("enteredBy");

                    b.Property<double?>("EnteredInsulin")
                        .HasColumnType("double precision")
                        .HasColumnName("enteredinsulin");

                    b.Property<string>("EventTime")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("eventTime");

                    b.Property<string>("EventType")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("eventType");

                    b.Property<double?>("Fat")
                        .HasColumnType("double precision")
                        .HasColumnName("fat");

                    b.Property<bool?>("First")
                        .HasColumnType("boolean")
                        .HasColumnName("first");

                    b.Property<string>("FoodType")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("foodType");

                    b.Property<double?>("Glucose")
                        .HasColumnType("double precision")
                        .HasColumnName("glucose");

                    b.Property<string>("GlucoseType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("glucoseType");

                    b.Property<double?>("Insulin")
                        .HasColumnType("double precision")
                        .HasColumnName("insulin");

                    b.Property<double?>("InsulinNeedsScaleFactor")
                        .HasColumnType("double precision")
                        .HasColumnName("insulinNeedsScaleFactor");

                    b.Property<bool?>("IsAnnouncement")
                        .HasColumnType("boolean")
                        .HasColumnName("isAnnouncement");

                    b.Property<double?>("Mgdl")
                        .HasColumnType("double precision")
                        .HasColumnName("mgdl");

                    b.Property<long>("Mills")
                        .HasColumnType("bigint")
                        .HasColumnName("mills");

                    b.Property<double?>("Mmol")
                        .HasColumnType("double precision")
                        .HasColumnName("mmol");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("NsClientId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("NSCLIENT_ID");

                    b.Property<string>("OriginalId")
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("original_id");

                    b.Property<double?>("Percent")
                        .HasColumnType("double precision")
                        .HasColumnName("percent");

                    b.Property<double?>("Percentage")
                        .HasColumnType("double precision")
                        .HasColumnName("percentage");

                    b.Property<double?>("PreBolus")
                        .HasColumnType("double precision")
                        .HasColumnName("preBolus");

                    b.Property<string>("Profile")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("profile");

                    b.Property<string>("ProfileJson")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("null")
                        .HasColumnName("profileJson");

                    b.Property<double?>("Protein")
                        .HasColumnType("double precision")
                        .HasColumnName("protein");

                    b.Property<double?>("Rate")
                        .HasColumnType("double precision")
                        .HasColumnName("rate");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<double?>("Relative")
                        .HasColumnType("double precision")
                        .HasColumnName("relative");

                    b.Property<string>("Source")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("source");

                    b.Property<string>("Split")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("split");

                    b.Property<double?>("SplitExt")
                        .HasColumnType("double precision")
                        .HasColumnName("splitExt");

                    b.Property<double?>("SplitNow")
                        .HasColumnType("double precision")
                        .HasColumnName("splitNow");

                    b.Property<string>("Status")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("status");

                    b.Property<DateTime>("SysCreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sys_created_at");

                    b.Property<DateTime>("SysUpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sys_updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<double?>("TargetBottom")
                        .HasColumnType("double precision")
                        .HasColumnName("targetBottom");

                    b.Property<double?>("TargetTop")
                        .HasColumnType("double precision")
                        .HasColumnName("targetTop");

                    b.Property<double?>("Timeshift")
                        .HasColumnType("double precision")
                        .HasColumnName("timeshift");

                    b.Property<long?>("Timestamp")
                        .HasColumnType("bigint")
                        .HasColumnName("timestamp");

                    b.Property<string>("TransmitterId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("transmitterId");

                    b.Property<string>("Units")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("units");

                    b.Property<int?>("UtcOffset")
                        .HasColumnType("integer")
                        .HasColumnName("utcOffset");

                    b.HasKey("Id");

                    b.HasIndex("EventType")
                        .HasDatabaseName("ix_treatments_event_type");

                    b.HasIndex("Mills")
                        .IsDescending()
                        .HasDatabaseName("ix_treatments_mills");

                    b.HasIndex("SysCreatedAt")
                        .HasDatabaseName("ix_treatments_sys_created_at");

                    b.HasIndex("EventType", "Mills")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_treatments_event_type_mills");

                    b.ToTable("treatments");
                });

            modelBuilder.Entity("Nocturne.Infrastructure.Data.Entities.AlertHistoryEntity", b =>
                {
                    b.HasOne("Nocturne.Infrastructure.Data.Entities.AlertRuleEntity", "AlertRule")
                        .WithMany("AlertHistory")
                        .HasForeignKey("AlertRuleId");

                    b.Navigation("AlertRule");
                });

            modelBuilder.Entity("Nocturne.Infrastructure.Data.Entities.DiscrepancyDetailEntity", b =>
                {
                    b.HasOne("Nocturne.Infrastructure.Data.Entities.DiscrepancyAnalysisEntity", "Analysis")
                        .WithMany("Discrepancies")
                        .HasForeignKey("AnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Analysis");
                });

            modelBuilder.Entity("Nocturne.Infrastructure.Data.Entities.AlertRuleEntity", b =>
                {
                    b.Navigation("AlertHistory");
                });

            modelBuilder.Entity("Nocturne.Infrastructure.Data.Entities.DiscrepancyAnalysisEntity", b =>
                {
                    b.Navigation("Discrepancies");
                });
#pragma warning restore 612, 618
        }
    }
}
