import { env } from "./env.ts";

export interface ApiResponse<T = unknown> {
  status: number;
  headers: Headers;
  body: T;
  text: string;
}

export type Credentials =
  | { kind: "bearer"; token: string }
  | { kind: "api-secret"; secret: string }
  | { kind: "cookie"; cookie: string }
  | { kind: "anonymous" };

export interface ApiClientOptions {
  /** Host the API resolves the tenant from; omit for the apex (tenantless) surface. */
  host?: string;
  credentials?: Credentials;
}

/**
 * A thin typed client over the API's HTTP surface. The generated NSwag client lives inside the
 * SvelteKit app (gitignored, regenerated by the API build), so specs speak HTTP directly and
 * type only what they assert on.
 */
export class ApiClient {
  readonly host?: string;
  readonly credentials: Credentials;

  constructor(opts: ApiClientOptions = {}) {
    this.host = opts.host;
    this.credentials = opts.credentials ?? { kind: "anonymous" };
  }

  with(credentials: Credentials): ApiClient {
    return new ApiClient({ host: this.host, credentials });
  }

  async request<T = unknown>(method: string, path: string, body?: unknown, headers: Record<string, string> = {}): Promise<ApiResponse<T>> {
    const h: Record<string, string> = { accept: "application/json", ...headers };
    // The API sits behind the web proxy or the gateway in every deployment; X-Forwarded-Host is
    // how it learns the tenant there, and Host is not settable from fetch.
    if (this.host) h["x-forwarded-host"] = this.host;
    if (body !== undefined) h["content-type"] = "application/json";
    switch (this.credentials.kind) {
      case "bearer":
        h.authorization = `Bearer ${this.credentials.token}`;
        break;
      case "api-secret":
        h["api-secret"] = this.credentials.secret;
        break;
      case "cookie":
        h.cookie = this.credentials.cookie;
        break;
    }
    const res = await fetch(env.apiUrl + path, {
      method,
      headers: h,
      body: body === undefined ? undefined : JSON.stringify(body),
      redirect: "manual",
    });
    const text = await res.text();
    let parsed: unknown = text;
    if (text && (res.headers.get("content-type") ?? "").includes("json")) {
      try {
        parsed = JSON.parse(text);
      } catch {
        parsed = text;
      }
    }
    return { status: res.status, headers: res.headers, body: parsed as T, text };
  }

  get<T = unknown>(path: string, headers?: Record<string, string>) {
    return this.request<T>("GET", path, undefined, headers);
  }
  post<T = unknown>(path: string, body?: unknown, headers?: Record<string, string>) {
    return this.request<T>("POST", path, body ?? {}, headers);
  }
  put<T = unknown>(path: string, body?: unknown) {
    return this.request<T>("PUT", path, body ?? {});
  }
  patch<T = unknown>(path: string, body?: unknown) {
    return this.request<T>("PATCH", path, body ?? {});
  }
  delete<T = unknown>(path: string) {
    return this.request<T>("DELETE", path);
  }

  /** Like {@link request} but throws with the response body on a non-2xx status. */
  async ok<T = unknown>(method: string, path: string, body?: unknown): Promise<T> {
    const res = await this.request<T>(method, path, body);
    if (res.status < 200 || res.status >= 300) {
      throw new Error(`${method} ${path} -> HTTP ${res.status}: ${res.text.slice(0, 500)}`);
    }
    return res.body;
  }
}

/** Polls until `probe` returns a truthy value or the timeout elapses. */
export async function eventually<T>(probe: () => Promise<T | undefined | null | false>, opts: { timeoutMs?: number; intervalMs?: number; what?: string } = {}): Promise<T> {
  const deadline = Date.now() + (opts.timeoutMs ?? 30_000);
  let last: unknown;
  while (Date.now() < deadline) {
    try {
      const value = await probe();
      if (value) return value;
    } catch (err) {
      last = err;
    }
    await new Promise((r) => setTimeout(r, opts.intervalMs ?? 250));
  }
  throw new Error(`timed out waiting for ${opts.what ?? "condition"}${last ? `: ${last}` : ""}`);
}
