<script lang="ts">
  import { onMount } from "svelte";
  import { resolve } from "$app/paths";
  import { ArrowLeft, HeartPulse, RefreshCw, Unplug } from "lucide-svelte";
  import type { GoogleHealthPreview, GoogleHealthStatus } from "$lib/api";
  import { Button } from "$lib/components/ui/button";
  import { Badge } from "$lib/components/ui/badge";
  import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "$lib/components/ui/card";
  import { describeGoogleHealthError, type GoogleHealthOperation } from "$lib/connectors/google-health-error";
  import { getPersonalGoogleHealth, savePersonalGoogleHealth, startPersonalGoogleHealth, disconnectPersonalGoogleHealth, syncPersonalGoogleHealth, previewPersonalGoogleHealth, purgePersonalGoogleHealth } from "$lib/api/generated/personalGoogleHealths.generated.remote";

  let status = $state<GoogleHealthStatus | null>(null), preview = $state<GoogleHealthPreview | null>(null);
  let clientId = $state(""), clientSecret = $state(""), callbackUrl = $state(""), importFrom = $state("");
  let selected = $state<string[]>(["steps", "heart-rate", "weight", "sleep"]), busy = $state(true), message = $state("");
  let operation: GoogleHealthOperation = "status";
  const labels: Record<string, string> = { steps: "Steps", "heart-rate": "Heart rate", weight: "Weight", sleep: "Sleep", "body-fat": "Body fat", distance: "Distance", "oxygen-saturation": "Oxygen saturation", "heart-rate-variability": "Heart rate variability" };
  const destinations: Record<string, string> = { "step-counts": "Step history", "heart-rates": "Heart-rate history", "body-weights": "Weight history", "sleep-sessions": "Sleep history" };
  const errors: Record<string, string> = {
    configure_first: "Save the Google configuration first.", invalid_configuration: "Check the client ID and import start date.", invalid_callback: "Use an HTTPS URL ending exactly in /personal/google/callback.",
    invalid_client_credentials: "Google rejected the client ID or secret.", oauth_scope_configuration: "Google rejected a requested Health scope.", oauth_request_invalid: "Google rejected the OAuth request.", invalid_token_response: "Google did not return a usable session.", client_secret_required: "A Google client secret is required.",
    connection_owner_required: "Only the user who created this connection can change it.", disconnect_first: "Disconnect before changing these settings.", account_mismatch: "This is a different Google account. Purge the old import before switching.", expired_signin: "The sign-in attempt expired. Start again.", offline_access_required: "Google did not grant background access. Revoke access and reconnect.", partial_consent: "Not every requested permission was granted.", permission_denied: "Google denied access.", reconnect_required: "Google access expired or was revoked. Reconnect.", rate_limited: "Google's request limit was reached. Nocturne will retry later.", google_unavailable: "Google is temporarily unavailable. Existing data was preserved.",
    account_not_linked: "This Google account is not linked to Fitbit.", invalid_google_request: "Google rejected the data request.", preview_access_denied: "This account cannot access this API version.", google_resource_not_found: "This data type is unavailable for this account.", data_access_denied: "Google does not permit this data type to be read.", invalid_time_range: "Google rejected this date range. Choose a later start date.", invalid_filter_operator: "Google rejected Nocturne's time filter.", invalid_google_filter: "Google rejected the filter for this data type.", invalid_google_data_type: "Google did not recognise this data type.", invalid_source_family: "Google could not reconcile the sources.", invalid_google_response: "Google returned an incomplete response.", no_google_data: "Google returned no measurements for this date range.", stored_google_configuration_unreadable: "The saved connection cannot be read. Configure it again.", unsupported_type: "The saved selection contains an unsupported type.", revoke_in_google: "Disconnected locally. Revoke the app in Google as well.", history_too_large: "This range contains too many measurements. Choose a later start date.", invalid_google_data: "Google returned an unexpected data format.", duplicate_google_data: "Google returned overlapping measurements.", unexpected_time_range: "Google returned data outside the requested range.", pagination_failed: "Nocturne could not retrieve every page.",
    internal_sync_connection_read: "Nocturne could not read the saved connection. Check the server log.", internal_sync_session_read: "Nocturne could not process the protected session. Check the server log.", internal_sync_token_refresh: "Refreshing the Google session failed. Check the server log.", internal_sync_scope_validation: "Checking permissions failed. Check the server log.", internal_sync_google_read: "Reading Google Health failed. Check the server log.", internal_sync_data_validation: "Validating Google data failed. Check the server log.", internal_sync_native_write: "Data could not be stored in Nocturne health records. Check the server log.", internal_sync_database_write: "Data could not be stored. Check the server log."
  };
  const day = (value?: string | Date | null) => value ? new Date(value).toISOString().slice(0, 10) : "";
  const options = (previewOnly: boolean) => ({ clientId, clientSecret: clientSecret || null, callbackUrl, dataTypes: selected, historyDays: 7, importFrom: importFrom ? `${importFrom}T00:00:00.000Z` : null, previewOnly });
  async function loadPreview() { operation = "readings"; preview = await previewPersonalGoogleHealth(); }
  async function refresh() { operation = "status"; status = await getPersonalGoogleHealth().run(); clientId = status.clientId ?? ""; callbackUrl = status.callbackUrl || `${location.origin}/personal/google/callback`; selected = status.configured ? status.selectedTypes ?? [] : selected; importFrom = day(status.importFrom) || day(new Date(Date.now() - (status.historyDays ?? 7) * 86400000)); if (status.connected) await loadPreview(); }
  async function run(action: () => Promise<unknown>) { busy = true; message = ""; try { await action(); } catch (error) { message = describeGoogleHealthError(error, operation, errors); } finally { busy = false; } }
  async function connect() { operation = "save"; await savePersonalGoogleHealth(options(true)); clientSecret = ""; operation = "signin"; const auth = await startPersonalGoogleHealth(); if (auth.url) location.assign(auth.url); }
  async function saveAndImport() { operation = "save"; await savePersonalGoogleHealth(options(false)); operation = "sync"; await syncPersonalGoogleHealth(); await refresh(); }
  async function disconnect() { operation = "disconnect"; await disconnectPersonalGoogleHealth(); preview = null; await refresh(); }
  function itemStatus(item: NonNullable<GoogleHealthPreview["items"]>[number]) { if (item.errorCode) return `Read failed (${item.errorCode})`; if (!item.supported) return "Not yet supported by Nocturne"; if (!item.granted) return "Permission not granted"; if (item.count > 0 && selected.includes(item.dataType ?? "")) return "Connected and importing"; if (item.count > 0) return "Available to connect"; return "Supported, but no data found"; }
  onMount(() => { let active = true; queueMicrotask(() => { if (active) void run(async () => { const outcome = new URLSearchParams(location.search).get("connection"); await refresh(); if (outcome === "failed") message = "Google sign-in failed or was cancelled."; if (outcome === "provider_denied") message = "Google did not grant the requested read access."; if (outcome === "no_session") message = "The Nocturne session was missing after the Google redirect. Sign in and reconnect in the same browser."; }); }); return () => { active = false; }; });
</script>

<svelte:head><title>Google Health · Connectors & Apps</title></svelte:head>
<section class="mx-auto max-w-5xl space-y-6 p-6">
  <a class="inline-flex items-center gap-2 text-sm text-muted-foreground" href={resolve("/settings/connectors")}><ArrowLeft class="h-4 w-4" />Connectors & Apps</a>
  <header class="flex items-start justify-between gap-4"><div class="flex items-center gap-3"><div class="rounded-lg bg-primary/10 p-3"><HeartPulse class="h-6 w-6 text-primary" /></div><div><h1 class="text-3xl font-semibold">Google Health</h1><p class="text-muted-foreground">Server connector for health and fitness data</p></div></div><Badge variant={status?.connected ? "default" : "outline"}>{status?.connected ? "Connected" : status?.configured ? "Configured" : "Not Configured"}</Badge></header>
  {#if message}<p role="alert" class="rounded-lg border border-destructive p-4">{message}</p>{/if}
  {#if status?.errorCode}<div role="status" class="rounded-lg border p-4"><p>{errors[status.errorCode] ?? "The import could not be completed."}</p><p class="mt-2 text-sm text-muted-foreground">Technical code: <code>{status.errorCode}</code>{status.errorDataTypes?.length ? ` · ${status.errorDataTypes.join(", ")}` : ""}</p></div>{/if}

  <Card><CardHeader><CardTitle>Connection</CardTitle><CardDescription>Read-only OAuth connection to the Google Health API</CardDescription></CardHeader><CardContent class="space-y-4">
    {#if !status}<p>Loading connection status…</p>{:else if !status.connected}
      {#if !status.configured}<form class="space-y-4" onsubmit={(event) => { event.preventDefault(); void run(connect); }}>
        <label class="block text-sm font-medium">Google client ID<input class="mt-1 w-full rounded border bg-background p-2" required bind:value={clientId} /></label>
        <label class="block text-sm font-medium">Client secret<input class="mt-1 w-full rounded border bg-background p-2" type="password" required bind:value={clientSecret} /></label>
        <label class="block text-sm font-medium">Callback URL<input class="mt-1 w-full rounded border bg-background p-2" type="url" required bind:value={callbackUrl} /></label>
        <label class="block text-sm font-medium">Import data from<input class="mt-1 block rounded border bg-background p-2" type="date" min="2000-01-01" max={day(new Date())} required bind:value={importFrom} /></label>
        <p class="text-sm text-muted-foreground">Nocturne retrieves every available page from this date. An early start date can make the first import take longer.</p><Button type="submit" disabled={busy}>Save and connect</Button>
      </form>{:else}<p>The encrypted Google Cloud configuration is saved.</p><div class="flex gap-2"><Button disabled={busy} onclick={() => void run(async () => { operation = "signin"; const auth = await startPersonalGoogleHealth(); if (auth.url) location.assign(auth.url); })}>Sign in with Google</Button><Button variant="outline" disabled={busy} onclick={() => void run(disconnect)}><Unplug class="mr-2 h-4 w-4" />Disconnect</Button></div>
        <details><summary class="cursor-pointer text-sm font-medium">Edit connection settings</summary><form class="mt-4 space-y-4" onsubmit={(event) => { event.preventDefault(); void run(connect); }}><label class="block text-sm font-medium">Google client ID<input class="mt-1 w-full rounded border bg-background p-2" required bind:value={clientId} /></label><label class="block text-sm font-medium">Client secret<input class="mt-1 w-full rounded border bg-background p-2" type="password" bind:value={clientSecret} placeholder="Leave empty to keep the saved secret" /></label><label class="block text-sm font-medium">Callback URL<input class="mt-1 w-full rounded border bg-background p-2" type="url" required bind:value={callbackUrl} /></label><label class="block text-sm font-medium">Import data from<input class="mt-1 block rounded border bg-background p-2" type="date" min="2000-01-01" max={day(new Date())} required bind:value={importFrom} /></label><Button type="submit" disabled={busy}>Save and reconnect</Button></form></details>{/if}
    {:else}<p>Google Health is connected. Automatic sync runs approximately every 15 minutes.</p><p class="text-sm text-muted-foreground">History start: {importFrom}. Disconnect first to change the date or OAuth settings.</p><div class="flex gap-2"><Button variant="outline" disabled={busy} onclick={() => void run(async () => { operation = "sync"; await syncPersonalGoogleHealth(); await refresh(); })}><RefreshCw class="mr-2 h-4 w-4" />Sync now</Button><Button variant="outline" disabled={busy} onclick={() => void run(disconnect)}><Unplug class="mr-2 h-4 w-4" />Disconnect</Button></div>{/if}
  </CardContent></Card>

  {#if status?.connected}<Card><CardHeader><CardTitle>Google Health data</CardTitle><CardDescription>Detected data types and how Nocturne can use them</CardDescription></CardHeader><CardContent class="space-y-4">
    {#if preview}<div class="overflow-auto"><table class="w-full text-left text-sm"><thead><tr class="border-b"><th class="p-3">Import</th><th class="p-3">Data type</th><th class="p-3">Found</th><th class="p-3">Nocturne destination</th><th class="p-3">Status</th></tr></thead><tbody>{#each preview.items ?? [] as item (item.dataType)}{@const capability = status.capabilities?.find((entry) => entry.dataType === item.dataType)}<tr class="border-b"><td class="p-3"><input aria-label={`Import ${labels[item.dataType ?? ""] ?? item.dataType}`} type="checkbox" bind:group={selected} value={item.dataType} disabled={!item.supported || !item.granted || item.count === 0 || !!item.errorCode} /></td><td class="p-3 font-medium">{labels[item.dataType ?? ""] ?? item.dataType}</td><td class="p-3">{item.errorCode || !item.granted ? "Unknown" : item.count > 0 ? `Yes (${item.count})` : "No"}</td><td class="p-3">{capability?.destination ? destinations[capability.destination] ?? capability.destination : "No destination yet"}</td><td class="p-3">{itemStatus(item)}</td></tr>{/each}</tbody></table></div>
      <div class="flex gap-2"><Button disabled={busy || selected.length === 0} onclick={() => void run(saveAndImport)}>Save selection and import</Button><Button variant="outline" disabled={busy} onclick={() => void run(loadPreview)}><RefreshCw class="mr-2 h-4 w-4" />Refresh inventory</Button></div>
    {:else}<p>Checking available data…</p>{/if}
  </CardContent></Card>{/if}

  <details class="rounded-lg border p-4"><summary class="cursor-pointer font-medium">Google Cloud setup</summary><ol class="mt-3 list-inside list-decimal space-y-2 text-sm"><li>Enable the Google Health API and create an OAuth Web application client.</li><li>Add your account as a test user while the consent screen is in testing.</li><li>Register the callback URL above as an Authorized redirect URI.</li><li>Keep the client secret private.</li></ol><a class="mt-3 inline-block underline" href="https://developers.google.com/health/setup" target="_blank" rel="noreferrer">Google setup documentation</a></details>
  {#if status?.configured && !status.connected}<Button variant="destructive" disabled={busy} onclick={() => { if (confirm("Permanently delete measurements imported through Google Health? Data in Google is unchanged.")) void run(async () => { operation = "purge"; await purgePersonalGoogleHealth(); await refresh(); }); }}>Delete imported Google Health data</Button>{/if}
</section>
