<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <Description>Nightscout data source connector service</Description>
    </PropertyGroup>
    <ItemGroup>
        <InternalsVisibleTo Include="Nocturne.Connectors.Nightscout.Tests"/>
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\..\Core\Nocturne.Core.Models\Nocturne.Core.Models.csproj"/>
        <ProjectReference Include="..\Nocturne.Connectors.Core\Nocturne.Connectors.Core.csproj"/>
    </ItemGroup>
</Project>
