import {
	AlertRuleSeverity,
	ChannelType,
	AlertConditionType,
	TempBasalMetric,
	GlucoseBucket,
	PumpModeState,
	StateSpanCategory,
	DayOfWeek,
	AlertComparisonOperator,
} from "$api-clients";
import type {
	AlertRuleResponse,
	ThresholdCondition,
	RateOfChangeCondition,
	SignalLossCondition,
	StalenessCondition,
	PredictedCondition,
	TrendCondition,
	TimeOfDayCondition,
	IobCondition,
	CobCondition,
	ReservoirCondition,
	SiteAgeCondition,
	SensorAgeCondition,
	AlertStateCondition,
	LoopStaleCondition,
	LoopEnactionStaleCondition,
	PumpSuspendedCondition,
	PumpBatteryCondition,
	TempBasalCondition,
	UploaderBatteryCondition,
	OverrideActiveCondition,
	SensitivityRatioCondition,
	DoNotDisturbCondition,
	GlucoseBucketCondition,
	TimeSinceLastCarbCondition,
	TimeSinceLastBolusCondition,
	DayOfWeekCondition,
	PumpStateCondition,
	StateSpanActiveCondition,
	TrackerAgeCondition,
	SleepSessionActiveCondition,
} from "$api-clients";

// All condition payload records are generated by NSwag from the C# records in
// `Nocturne.Core.Models.AlertModels` (see the [JsonPropertyName] attributes there
// pinning the wire names to snake_case). Editor-only adornments live here only
// where they don't exist on the wire — currently just `_uid`.

export { TempBasalMetric, GlucoseBucket, PumpModeState, StateSpanCategory, DayOfWeek };
export type {
	ThresholdCondition,
	RateOfChangeCondition,
	SignalLossCondition,
	StalenessCondition,
	PredictedCondition,
	TrendCondition,
	TimeOfDayCondition,
	IobCondition,
	CobCondition,
	ReservoirCondition,
	SiteAgeCondition,
	SensorAgeCondition,
	AlertStateCondition,
	LoopStaleCondition,
	LoopEnactionStaleCondition,
	PumpSuspendedCondition,
	PumpBatteryCondition,
	TempBasalCondition,
	UploaderBatteryCondition,
	OverrideActiveCondition,
	SensitivityRatioCondition,
	DoNotDisturbCondition,
	GlucoseBucketCondition,
	TimeSinceLastCarbCondition,
	TimeSinceLastBolusCondition,
	DayOfWeekCondition,
	PumpStateCondition,
	StateSpanActiveCondition,
	TrackerAgeCondition,
	SleepSessionActiveCondition,
};

/**
 * The set of valid {@link ConditionNode.type} values. Mirrors the backend
 * <c>AlertConditionType</c> enum — kebab-/snake-case strings.
 */
export type ConditionKind = `${AlertConditionType}`;

export type ComparisonOperator = ">=" | ">" | "<=" | "<";

/** Narrows an arbitrary value to a member of a string-valued enum. */
export function isStringEnumMember<E extends Record<string, string>>(
	enumObject: E,
	value: unknown,
): value is E[keyof E] {
	return (
		typeof value === "string" &&
		Object.values(enumObject).some((member) => member === value)
	);
}

/** The generated enum member for a condition kind; the two are the same strings. */
export function toAlertConditionType(kind: ConditionKind): AlertConditionType | undefined {
	return Object.values(AlertConditionType).find((member) => member === kind);
}

/**
 * Staleness is conceptually directional ("more than N minutes since…"), so the
 * loop-staleness kinds only accept `>` and `>=`. The wider {@link StalenessCondition}
 * (BG staleness) was shipped accepting all four operators and predates this
 * narrowing; widening would break stored rules using `<` for auto-resolve.
 */
export type StalenessOperator = ">" | ">=";

export type TrendBucket =
	| "falling_fast"
	| "falling"
	| "flat"
	| "rising"
	| "rising_fast";

const TREND_BUCKETS: readonly TrendBucket[] = [
	"falling_fast",
	"falling",
	"flat",
	"rising",
	"rising_fast",
];

export function isTrendBucket(value: unknown): value is TrendBucket {
	return TREND_BUCKETS.some((bucket) => bucket === value);
}

/**
 * Composite condition (AND/OR group). The wire-side child list points back at
 * the editor's {@link ConditionNode}, not the bare generated record, so the
 * `_uid` extension propagates through nested groups.
 */
export interface CompositePayload {
	operator: "and" | "or";
	conditions: ConditionNode[];
}

export interface NotPayload {
	child: ConditionNode;
}

export interface SustainedPayload {
	minutes: number;
	child: ConditionNode;
}

/**
 * The editor's recursive condition tree. Field shapes for leaf nodes come
 * straight from the generated client; the only editor-only addition is `_uid`,
 * stripped before the tree is sent back over the wire (see
 * {@link stripEditorFields}).
 *
 * `composite`/`not`/`sustained` use editor-aware payloads here so the `_uid`
 * extension propagates through nested groups — the generated wire types refer
 * to a bare `ConditionNode` without it.
 */
export interface ConditionNode {
	type: ConditionKind;
	/**
	 * Editor-only stable identity for keyed `{#each}` blocks. Set on
	 * construction (`defaultPayload`/`nodeFromApi`); stripped before the node
	 * is sent over the wire by {@link stripEditorFields}. Index-based keys
	 * cause Svelte 5 to re-bind the wrong nested editor instance after a
	 * sibling is removed; this avoids that.
	 */
	_uid?: string;
	composite?: CompositePayload;
	not?: NotPayload;
	sustained?: SustainedPayload;
	threshold?: ThresholdCondition;
	rate_of_change?: RateOfChangeCondition;
	signal_loss?: SignalLossCondition;
	staleness?: StalenessCondition;
	predicted?: PredictedCondition;
	trend?: TrendCondition;
	time_of_day?: TimeOfDayCondition;
	iob?: IobCondition;
	cob?: CobCondition;
	reservoir?: ReservoirCondition;
	site_age?: SiteAgeCondition;
	sensor_age?: SensorAgeCondition;
	alert_state?: AlertStateCondition;
	loop_stale?: LoopStaleCondition;
	loop_enaction_stale?: LoopEnactionStaleCondition;
	pump_suspended?: PumpSuspendedCondition;
	pump_battery?: PumpBatteryCondition;
	temp_basal?: TempBasalCondition;
	uploader_battery?: UploaderBatteryCondition;
	override_active?: OverrideActiveCondition;
	sensitivity_ratio?: SensitivityRatioCondition;
	do_not_disturb?: DoNotDisturbCondition;
	glucose_bucket?: GlucoseBucketCondition;
	time_since_last_carb?: TimeSinceLastCarbCondition;
	time_since_last_bolus?: TimeSinceLastBolusCondition;
	day_of_week?: DayOfWeekCondition;
	pump_state?: PumpStateCondition;
	state_span_active?: StateSpanActiveCondition;
	sleep_session_active?: SleepSessionActiveCondition;
	tracker_age?: TrackerAgeCondition;
}

/** Builds a node of <paramref name="kind"/> carrying its payload under the matching key. */
export function withPayload<K extends ConditionKind>(
	kind: K,
	payload: NonNullable<ConditionNode[K]>,
): ConditionNode {
	const node: ConditionNode = { type: kind };
	Object.assign(node, { [kind]: payload });
	return node;
}

// randomUUID exists only in secure contexts; a LAN install served over plain
// http still has getRandomValues.
function newUid(): string {
	if (typeof crypto.randomUUID === "function") return crypto.randomUUID();
	return Array.from(crypto.getRandomValues(new Uint8Array(16)), (b) =>
		b.toString(16).padStart(2, "0"),
	).join("");
}

/**
 * Wrap a non-composite node in a single-child AND group, leaving composite
 * nodes untouched. The inline rule builder always edits at the group level —
 * single-leaf rules are still rendered as one IF row inside an implicit AND.
 * The save path (caller-side) flattens single-child composites back to the
 * inner node so the wire shape doesn't grow a redundant wrapper.
 */
export function ensureCompositeRoot(node: ConditionNode): ConditionNode {
	if (node.type === "composite") return node;
	return {
		type: "composite",
		_uid: newUid(),
		composite: { operator: "and", conditions: [node] },
	};
}

/**
 * Inverse of {@link ensureCompositeRoot}. Returns the inner node when the root
 * is a composite holding exactly one child; otherwise returns the input
 * unchanged. Use this when serialising the editor's tree back to the API so
 * single-leaf rules stay flat on the wire.
 */
export function flattenSingleChildRoot(node: ConditionNode): ConditionNode {
	const conditions = node.type === "composite" ? node.composite?.conditions : undefined;
	const only: unknown = conditions?.length === 1 ? conditions[0] : undefined;
	return isConditionNode(only) ? only : node;
}

// ---------------------------------------------------------------------------
// Default payloads per kind
// ---------------------------------------------------------------------------

export function defaultPayload(kind: ConditionKind): ConditionNode {
	const node = makeDefault(kind);
	node._uid = newUid();
	return node;
}

function makeDefault(kind: ConditionKind): ConditionNode {
	switch (kind) {
		case "composite":
			return {
				type: "composite",
				composite: {
					operator: "and",
					conditions: [defaultPayload("threshold")],
				},
			};
		case "not":
			return { type: "not", not: { child: defaultPayload("threshold") } };
		case "sustained":
			return {
				type: "sustained",
				sustained: { minutes: 15, child: defaultPayload("threshold") },
			};
		case "threshold":
			return {
				type: "threshold",
				threshold: { direction: "below", value: 70 },
			};
		case "rate_of_change":
			return {
				type: "rate_of_change",
				rate_of_change: { direction: "falling", rate: 3 },
			};
		case "staleness":
			return {
				type: "staleness",
				staleness: { operator: ">=", value: 15 },
			};
		case "predicted":
			return {
				type: "predicted",
				predicted: { operator: "<=", value: 70, within_minutes: 30 },
			};
		case "trend":
			return { type: "trend", trend: { bucket: "falling" } };
		case "time_of_day":
			// Stamp the browser's IANA timezone at creation time so the saved rule JSON is
			// self-documenting and survives a future tenant tz change. Without one the
			// backend evaluates in the tenant's zone.
			return {
				type: "time_of_day",
				time_of_day: { from: "22:00", to: "06:00", timezone: browserTimeZone() },
			};
		case "iob":
			return { type: "iob", iob: { operator: ">=", value: 1 } };
		case "cob":
			return { type: "cob", cob: { operator: ">=", value: 10 } };
		case "reservoir":
			return {
				type: "reservoir",
				reservoir: { operator: "<=", value: 10 },
			};
		case "site_age":
			return {
				type: "site_age",
				site_age: { operator: ">=", value: 72 },
			};
		case "sensor_age":
			return {
				type: "sensor_age",
				sensor_age: { operator: ">=", value: 10 },
			};
		case "alert_state":
			return {
				type: "alert_state",
				alert_state: { alert_id: "", state: "firing" },
			};
		case "loop_stale":
			return {
				type: "loop_stale",
				loop_stale: { operator: ">", minutes: 15 },
			};
		case "loop_enaction_stale":
			return {
				type: "loop_enaction_stale",
				loop_enaction_stale: { operator: ">", minutes: 15 },
			};
		case "pump_suspended":
			return {
				type: "pump_suspended",
				pump_suspended: { is_active: true },
			};
		case "pump_battery":
			return {
				type: "pump_battery",
				pump_battery: { operator: "<=", value: 20 },
			};
		case "temp_basal":
			return {
				type: "temp_basal",
				temp_basal: { metric: TempBasalMetric.Rate, operator: ">=", value: 1 },
			};
		case "uploader_battery":
			return {
				type: "uploader_battery",
				uploader_battery: { operator: "<=", value: 20 },
			};
		case "override_active":
			return {
				type: "override_active",
				override_active: { is_active: true },
			};
		case "sensitivity_ratio":
			return {
				type: "sensitivity_ratio",
				sensitivity_ratio: { operator: "<", value: 0.8 },
			};
		case "do_not_disturb":
			return {
				type: "do_not_disturb",
				do_not_disturb: { is_active: true },
			};
		case "signal_loss":
			return {
				type: "signal_loss",
				signal_loss: { timeout_minutes: 30 },
			};
		case "glucose_bucket":
			return {
				type: "glucose_bucket",
				glucose_bucket: { buckets: [GlucoseBucket.Low] },
			};
		case "time_since_last_carb":
			return {
				type: "time_since_last_carb",
				time_since_last_carb: {
					operator: AlertComparisonOperator.Gte,
					minutes: 30,
				},
			};
		case "time_since_last_bolus":
			return {
				type: "time_since_last_bolus",
				time_since_last_bolus: {
					operator: AlertComparisonOperator.Gte,
					minutes: 60,
				},
			};
		case "day_of_week":
			return {
				type: "day_of_week",
				day_of_week: { days: [DayOfWeek.Monday] },
			};
		case "pump_state":
			return {
				type: "pump_state",
				pump_state: { mode: PumpModeState.Suspended, is_active: true },
			};
		case "state_span_active":
			return {
				type: "state_span_active",
				state_span_active: {
					category: StateSpanCategory.Override,
					is_active: true,
				},
			};
		case "sleep_session_active":
			return {
				type: "sleep_session_active",
				sleep_session_active: { is_active: true },
			};
		case "tracker_age":
			return {
				type: "tracker_age",
				tracker_age: {
					tracker_definition_id: "",
					operator: ">=",
					minutes: 0,
				},
			};
	}
}

/**
 * The browser's IANA timezone, or `undefined` when it reports none a rule can be
 * evaluated in (`Etc/Unknown`, or an id `Intl` itself rejects), so the rule
 * falls back to the tenant's zone instead of being refused on save.
 */
export function browserTimeZone(): string | undefined {
	if (typeof Intl === "undefined") return undefined;
	const zone = Intl.DateTimeFormat().resolvedOptions().timeZone;
	if (!zone || zone === "Etc/Unknown") return undefined;
	try {
		new Intl.DateTimeFormat("en", { timeZone: zone });
		return zone;
	} catch {
		return undefined;
	}
}

const comparisonShown = { operator: ">=", value: 0 };
const inactiveShown = { is_active: false };

/**
 * What `RuleBuilderLeafEditor` shows for a leaf field a stored rule leaves out,
 * which {@link nodeFromApi} writes into the model so that saving sends what was
 * shown. A missing `is_active` is `false`, as the engines read it; a new leaf
 * is created with it set.
 */
const SHOWN_DEFAULTS: Partial<Record<ConditionKind, Record<string, unknown>>> = {
	threshold: { direction: "below", value: 0 },
	predicted: { operator: "<=", value: 0, within_minutes: 0 },
	rate_of_change: { direction: "falling", rate: 0 },
	trend: { bucket: "falling" },
	staleness: comparisonShown,
	time_of_day: { from: "00:00", to: "23:59" },
	iob: comparisonShown,
	cob: comparisonShown,
	reservoir: comparisonShown,
	site_age: comparisonShown,
	sensor_age: comparisonShown,
	pump_battery: comparisonShown,
	uploader_battery: comparisonShown,
	sensitivity_ratio: comparisonShown,
	loop_stale: { operator: ">", minutes: 0 },
	loop_enaction_stale: { operator: ">", minutes: 0 },
	signal_loss: { timeout_minutes: 0 },
	temp_basal: { metric: TempBasalMetric.Rate, operator: ">=", value: 0 },
	alert_state: { state: "firing" },
	time_since_last_carb: { operator: AlertComparisonOperator.Gte, minutes: 0 },
	time_since_last_bolus: { operator: AlertComparisonOperator.Gte, minutes: 0 },
	pump_suspended: inactiveShown,
	override_active: inactiveShown,
	do_not_disturb: inactiveShown,
	sleep_session_active: inactiveShown,
	pump_state: { mode: PumpModeState.Suspended, is_active: false },
	state_span_active: { category: StateSpanCategory.Override, is_active: false },
	tracker_age: { operator: ">=", minutes: 0 },
};

function fillShownDefaults(node: ConditionNode): void {
	const defaults = SHOWN_DEFAULTS[node.type];
	const payload: unknown = Reflect.get(node, node.type);
	if (!defaults || !isRecord(payload)) return;
	for (const [field, value] of Object.entries(defaults)) {
		if (payload[field] === undefined || payload[field] === null) payload[field] = value;
	}
}

// ---------------------------------------------------------------------------
// (De)serialise to/from API conditionParams field
// ---------------------------------------------------------------------------

/**
 * Wrap a full <see cref="ConditionNode"/> envelope (i.e. `{type, ...payload}`)
 * coming back from the API into the editor's tree. Used by save/load paths
 * where the wire shape is a self-describing envelope rather than a side-by-
 * side `(conditionType, conditionParams)` pair — notably auto-resolve, which
 * stores a single `autoResolveParams` blob the backend deserialises directly
 * into a polymorphic <see cref="ConditionNode"/>.
 */
export function nodeFromApiEnvelope(envelope: unknown): ConditionNode | null {
	if (!isRecord(envelope)) return null;
	const kind = envelope.type;
	if (typeof kind !== "string") return null;
	const payload: unknown = Reflect.get(envelope, kind);
	return nodeFromApi(kind, payload);
}

function isRecord(value: unknown): value is Record<string, unknown> {
	return typeof value === "object" && value !== null;
}

/** A value the editor holds as a node: an object with a string `type`. */
function isConditionNode(value: unknown): value is ConditionNode {
	return isRecord(value) && typeof value.type === "string";
}

/**
 * The one place a condition read off the wire is adopted as typed. The
 * generated client types rule condition JSON as `any`, and the editor takes it
 * as-is. Rejecting a rule it cannot fully validate would load the default
 * condition in its place, and saving would then overwrite the stored one.
 */
function adoptWireNode(raw: { type: string; [key: string]: unknown }): ConditionNode {
	// eslint-disable-next-line @typescript-eslint/consistent-type-assertions -- trust boundary, see above
	return raw as ConditionNode;
}

/**
 * Wrap a kind + opaque API payload into a `ConditionNode`. The API stores only
 * the kind-specific payload (e.g. `{direction, value}`); the FE keeps the kind
 * alongside it so a single recursive editor can dispatch on `node.type`.
 */
export function nodeFromApi(
	kind: string | undefined,
	params: unknown,
): ConditionNode | null {
	if (!kind) return null;
	if (params === null || params === undefined) return null;
	const node = adoptWireNode({ type: kind, _uid: newUid(), [kind]: params });
	// Defensive: a malformed loop-staleness rule with a `<`/`<=` operator would
	// render an unselectable value in the editor (the dropdown only offers `>`
	// and `>=`). Coerce on inbound and warn so we notice if it ever happens.
	coerceStalenessOperator(node);
	adoptTree(node);
	return node;
}

function coerceStalenessOperator(node: ConditionNode): void {
	const payload =
		node.type === "loop_stale"
			? node.loop_stale
			: node.type === "loop_enaction_stale"
				? node.loop_enaction_stale
				: null;
	if (!payload) return;
	const op = payload.operator;
	if (op === "<" || op === "<=") {
		console.warn(
			`[alerts] coercing ${node.type} operator '${op}' → '>' (staleness only supports '>' / '>=')`,
		);
		payload.operator = ">";
	}
}

/**
 * Gives every node of a tree read off the wire a `_uid`, so keyed each-blocks
 * have stable identity at every level, and its {@link SHOWN_DEFAULTS}.
 */
function adoptTree(node: ConditionNode): void {
	if (!node._uid) node._uid = newUid();
	fillShownDefaults(node);
	for (const child of childrenOf(node)) adoptTree(child);
}

/**
 * The nodes directly under `node`. A stored group can lack its list or child,
 * and a list can hold `null` slots; those contribute nothing.
 */
function childrenOf(node: ConditionNode): ConditionNode[] {
	const children: unknown[] =
		node.type === "composite"
			? (node.composite?.conditions ?? [])
			: node.type === "not"
				? [node.not?.child]
				: node.type === "sustained"
					? [node.sustained?.child]
					: [];
	return children.filter(isConditionNode);
}

/**
 * Returns a deep copy of `node` with every editor-only `_uid` field stripped.
 * Use this when sending the full ConditionNode envelope to the backend (e.g.
 * `autoResolveParams`) so the editor's internal identity doesn't leak into
 * stored configuration.
 */
export function stripEditorFields(node: ConditionNode): ConditionNode {
	const { _uid: _, ...cleaned } = node;
	for (const [key, value] of Object.entries(cleaned)) {
		if (value === undefined) Reflect.deleteProperty(cleaned, key);
	}
	// Recurse into nested children so uids in the subtree are also stripped. A
	// stored group missing its list or child keeps it missing, for the save to report.
	if (node.composite) {
		cleaned.composite = {
			...node.composite,
			conditions: node.composite.conditions?.map((c) =>
				isConditionNode(c) ? stripEditorFields(c) : c,
			),
		};
	}
	if (node.not) {
		const child: unknown = node.not.child;
		cleaned.not = { ...node.not, child: isConditionNode(child) ? stripEditorFields(child) : node.not.child };
	}
	if (node.sustained) {
		const child: unknown = node.sustained.child;
		cleaned.sustained = {
			...node.sustained,
			child: isConditionNode(child) ? stripEditorFields(child) : node.sustained.child,
		};
	}
	return cleaned;
}

/**
 * Removes every group the editor has left with no conditions, and any NOT or
 * sustained wrapper whose child that removes. An empty group is not part of the
 * rule the person sees, and the server rejects one. Returns `null` when nothing
 * is left.
 */
function withoutEmptyGroups(node: ConditionNode): ConditionNode | null {
	if (node.type === "composite" && node.composite) {
		const conditions = childrenOf(node)
			.map(withoutEmptyGroups)
			.filter((c): c is ConditionNode => c !== null);
		if (conditions.length === 0) return null;
		return { ...node, composite: { ...node.composite, conditions } };
	}
	if (node.type === "not" && node.not) {
		const [inner] = childrenOf(node);
		const child = inner ? withoutEmptyGroups(inner) : null;
		return child ? { ...node, not: { ...node.not, child } } : null;
	}
	if (node.type === "sustained" && node.sustained) {
		const [inner] = childrenOf(node);
		const child = inner ? withoutEmptyGroups(inner) : null;
		return child ? { ...node, sustained: { ...node.sustained, child } } : null;
	}
	return node;
}

/**
 * {@link flattenSingleChildRoot} after {@link withoutEmptyGroups}. A root with
 * nothing left keeps its empty group, so the save reports that the rule has no
 * conditions rather than sending none.
 */
function serialisableRoot(node: ConditionNode): ConditionNode {
	return flattenSingleChildRoot(withoutEmptyGroups(node) ?? node);
}

/**
 * Extract the kind-specific payload for the API. Returns `null` when there's
 * no node.
 */
export function nodeToApi(
	node: ConditionNode | null,
): { conditionType: ConditionKind; conditionParams: unknown } | null {
	if (!node) return null;
	const params = node[node.type];
	return { conditionType: node.type, conditionParams: params ?? {} };
}

/**
 * Serialise the editor's {@link RuleEditorState} into the wire-format body
 * shared by {@link CreateAlertRuleRequest} and {@link UpdateAlertRuleRequest}.
 *
 * Strips `_uid` markers and flattens single-child composite roots so the output
 * is identical for any two semantically-equal editor states regardless of their
 * internal identity markers. Use this both for the actual save call and for
 * dirty detection (compare `JSON.stringify` of current vs. saved body).
 */
export function buildBody(state: RuleEditorState) {
	const api = nodeToApi(stripEditorFields(serialisableRoot(state.condition!)));
	return {
		name: state.name,
		description: state.description || undefined,
		conditionType: api ? toAlertConditionType(api.conditionType) : undefined,
		conditionParams: api?.conditionParams,
		isEnabled: state.isEnabled,
		sortOrder: state.sortOrder,
		severity: state.severity,
		allowThroughDnd: state.allowThroughDnd,
		autoResolveEnabled: state.autoResolveEnabled,
		autoResolveParams: state.autoResolveCondition
			? stripEditorFields(serialisableRoot(state.autoResolveCondition))
			: undefined,
		clientConfiguration: {
			...state.clientConfig,
			snooze: {
				...state.clientConfig.snooze,
				conditions: state.clientConfig.snooze.conditions
					.map(withoutEmptyGroups)
					.filter((c): c is ConditionNode => c !== null)
					.map((c) => stripEditorFields(flattenSingleChildRoot(c))),
			},
		},
		channels: state.channels.map((c) => ({
			channelType: c.channelType,
			destination: c.destination || undefined,
			destinationLabel: c.destinationLabel || undefined,
			// device_action carries its selected capabilities as a JSON object;
			// the server serialises it to JSONB. Omit for channels without metadata.
			metadata: c.metadata ?? undefined,
			// Omitted keeps the stored secret, empty clears it — the editor only ever
			// knows whether one exists, never what it is.
			secret: c.secret ? c.secret : c.hasSecret ? undefined : "",
		})),
	};
}

/**
 * Applies a destination edit to a channel row. A stored secret is held against the
 * channel's type and destination, so retyping the destination leaves it behind — the
 * row must stop reporting a saved secret unless the editor is carrying a replacement
 * the user typed.
 */
export function applyChannelDestination(channel: ChannelDef, destination: string): void {
	if (channel.hasSecret && !channel.secret && destination !== channel.destination) {
		channel.hasSecret = false;
	}
	channel.destination = destination;
}

/**
 * Client-side pre-save validation for the channel list. Returns a message
 * describing the first invalid channel, or `null` when the list is saveable.
 * Mirrors the server's rejection of a device_action channel without a kind so
 * the editor can block the save instead of surfacing a generic 400.
 */
export function validateChannels(channels: ChannelDef[]): string | null {
	for (const c of channels) {
		if (c.channelType === ChannelType.DeviceAction && !c.destination) {
			return "The Device channel has no device kind selected. Choose a kind or remove the channel.";
		}
	}
	return null;
}

// ---------------------------------------------------------------------------
// Existing client-config / schedule shapes (unchanged)
// ---------------------------------------------------------------------------

export interface AudioConfig {
	enabled: boolean;
	sound: string;
	customSoundId: string | null;
	ascending: boolean;
	startVolume: number;
	maxVolume: number;
	ascendDurationSeconds: number;
	repeatCount: number;
}

export interface VisualConfig {
	flashEnabled: boolean;
	flashColor: string;
	persistentBanner: boolean;
	wakeScreen: boolean;
}

export interface SnoozeConfig {
	defaultMinutes: number;
	options: number[];
	maxCount: number;
	smartSnooze: boolean;
	smartSnoozeExtendMinutes: number;
	/**
	 * Optional conditions that must all hold for the snooze to extend. When
	 * empty, the backend falls back to the trend-favorable heuristic.
	 */
	conditions: ConditionNode[];
}

export interface ClientConfiguration {
	audio: AudioConfig;
	visual: VisualConfig;
	snooze: SnoozeConfig;
}

/**
 * Editor-shape for a single delivery channel. Mirrors the API's
 * <c>AlertRuleChannelResponse</c> minus the server-managed <c>id</c> and
 * <c>sortOrder</c> — the editor maintains list order positionally.
 *
 * <c>_uid</c> is an editor-only stable identity used as the key in
 * <c>{#each channels (ch._uid)}</c> blocks; without it, keying by index
 * causes Svelte 5 to re-bind input elements to the wrong row when channels
 * are removed mid-list. Stripped before sending over the wire.
 */
export interface ChannelDef {
	_uid?: string;
	channelType: ChannelType;
	destination: string;
	destinationLabel?: string | null;
	/**
	 * Channel-specific config persisted as JSONB on the wire. For
	 * <c>device_action</c> channels this is <c>{ capabilities: string[] }</c>;
	 * other channel kinds leave it undefined. Sent as a JSON object — the server
	 * serialises it; do not pre-stringify.
	 */
	metadata?: DeviceActionMetadata | null;
	/** Signing secret typed into the webhook editor. Write-only; never read back. */
	secret?: string;
	/**
	 * Whether a stored signing secret backs this channel. Loaded from the server and
	 * cleared by the editor's remove action, which is what distinguishes "keep the
	 * secret I was never shown" from "there should be no secret".
	 */
	hasSecret?: boolean;
}

/** Metadata shape for a <c>device_action</c> channel. */
export interface DeviceActionMetadata {
	capabilities: string[];
}

export interface RuleEditorState {
	name: string;
	description: string;
	severity: AlertRuleSeverity;
	condition: ConditionNode | null;
	autoResolveEnabled: boolean;
	autoResolveCondition: ConditionNode | null;
	sortOrder: number;
	isEnabled: boolean;
	clientConfig: ClientConfiguration;
	/** Flat list of delivery channels. */
	channels: ChannelDef[];
	/** When true, this rule still fires while the tenant is in Do Not Disturb
	 *  mode. Critical-severity rules implicitly bypass DND regardless. */
	allowThroughDnd: boolean;
}

export function defaultClientConfig(): ClientConfiguration {
	return {
		audio: {
			enabled: true,
			sound: "alarm-default",
			customSoundId: null,
			ascending: false,
			startVolume: 50,
			maxVolume: 80,
			ascendDurationSeconds: 30,
			repeatCount: 2,
		},
		visual: {
			flashEnabled: false,
			flashColor: "#ff0000",
			persistentBanner: true,
			wakeScreen: false,
		},
		snooze: {
			defaultMinutes: 15,
			options: [5, 15, 30, 60],
			maxCount: 3,
			smartSnooze: false,
			smartSnoozeExtendMinutes: 10,
			conditions: [],
		},
	};
}

export function defaultChannels(): ChannelDef[] {
	return [
		{
			_uid: newUid(),
			channelType: ChannelType.WebPush,
			destination: "",
			destinationLabel: "",
		},
	];
}

function defaultState(): RuleEditorState {
	return {
		name: "",
		description: "",
		severity: AlertRuleSeverity.Warning,
		condition: ensureCompositeRoot(defaultPayload("threshold")),
		autoResolveEnabled: false,
		autoResolveCondition: null,
		sortOrder: 0,
		isEnabled: true,
		clientConfig: defaultClientConfig(),
		channels: defaultChannels(),
		allowThroughDnd: false,
	};
}

/**
 * Snooze conditions are a frontend-only client-config extension. NSwag's
 * generated type for `clientConfiguration.snooze` doesn't model them, so we
 * read them off the raw object defensively.
 */
function parseSnoozeConditions(snooze: unknown): ConditionNode[] {
	if (!isRecord(snooze)) return [];
	const raw = snooze.conditions;
	if (!Array.isArray(raw)) return [];
	const out: ConditionNode[] = [];
	for (const entry of raw) {
		if (isRecord(entry) && typeof entry.type === "string") {
			// Normalise to a composite root: the inline rule builder always edits
			// at the group level, and pre-existing snooze entries (which were
			// stored as flat leaves under the legacy SnoozeTab) need wrapping
			// before they can be mounted.
			const node = ensureCompositeRoot(
				adoptWireNode({ ...entry, type: entry.type }),
			);
			adoptTree(node);
			out.push(node);
		}
	}
	return out;
}

/**
 * Normalise a channel's wire `metadata` into the editor's {@link DeviceActionMetadata}.
 * The server returns it as already-deserialised JSON (an object), but it may also
 * arrive as a string on older rows; handle both and keep only a valid
 * `capabilities` string array. Returns `null` when there's nothing usable.
 */
export function parseChannelMetadata(raw: unknown): DeviceActionMetadata | null {
	if (raw === null || raw === undefined) return null;
	let obj: unknown = raw;
	if (typeof raw === "string") {
		try {
			obj = JSON.parse(raw);
		} catch {
			return null;
		}
	}
	if (!isRecord(obj)) return null;
	const caps = obj.capabilities;
	if (!Array.isArray(caps)) return null;
	const capabilities = caps.filter((c): c is string => typeof c === "string");
	return { capabilities };
}

export function parseRule(r: AlertRuleResponse | null): RuleEditorState {
	if (!r) return defaultState();

	const rawCondition =
		nodeFromApi(r.conditionType, r.conditionParams) ?? defaultPayload("threshold");
	// The inline rule builder always edits at the group level, so wrap leaf
	// roots in a single-child AND group on the way in. The corresponding
	// flattenSingleChildRoot is applied on save by the caller.
	const condition = ensureCompositeRoot(rawCondition);
	// Auto-resolve is stored as a full ConditionNode envelope (the backend
	// deserialises r.autoResolveParams directly into a polymorphic node) — read
	// it through the envelope helper, then normalise to a composite root so
	// the inline rule builder can edit it in place.
	const rawAutoResolve = nodeFromApiEnvelope(r.autoResolveParams);
	const autoResolveCondition = rawAutoResolve ? ensureCompositeRoot(rawAutoResolve) : null;

	// Client configuration
	const cc = r.clientConfiguration;
	const clientConfig: ClientConfiguration = cc
		? {
				audio: {
					enabled: cc.audio?.enabled ?? true,
					sound: cc.audio?.sound ?? "alarm-default",
					customSoundId: cc.audio?.customSoundId ?? null,
					ascending: cc.audio?.ascending ?? false,
					startVolume: cc.audio?.startVolume ?? 50,
					maxVolume: cc.audio?.maxVolume ?? 80,
					ascendDurationSeconds: cc.audio?.ascendDurationSeconds ?? 30,
					repeatCount: cc.audio?.repeatCount ?? 2,
				},
				visual: {
					flashEnabled: cc.visual?.flashEnabled ?? false,
					flashColor: cc.visual?.flashColor ?? "#ff0000",
					persistentBanner: cc.visual?.persistentBanner ?? true,
					wakeScreen: cc.visual?.wakeScreen ?? false,
				},
				snooze: {
					defaultMinutes: cc.snooze?.defaultMinutes ?? 15,
					options: cc.snooze?.options ?? [5, 15, 30, 60],
					maxCount: cc.snooze?.maxCount ?? 3,
					smartSnooze: cc.snooze?.smartSnooze ?? false,
					smartSnoozeExtendMinutes: cc.snooze?.smartSnoozeExtendMinutes ?? 10,
					conditions: parseSnoozeConditions(cc.snooze),
				},
			}
		: defaultClientConfig();

	// Channels (flat per-rule)
	const channels: ChannelDef[] =
		(r.channels ?? [])
			.slice()
			.sort((a, b) => (a.sortOrder ?? 0) - (b.sortOrder ?? 0))
			.map((c) => ({
				_uid: newUid(),
				channelType: c.channelType ?? ChannelType.WebPush,
				destination: c.destination ?? "",
				destinationLabel: c.destinationLabel ?? "",
				metadata: parseChannelMetadata(c.metadata),
				hasSecret: c.hasSecret ?? false,
			}));

	return {
		name: r.name ?? "",
		description: r.description ?? "",
		severity: r.severity ?? AlertRuleSeverity.Warning,
		isEnabled: r.isEnabled ?? true,
		sortOrder: r.sortOrder ?? 0,
		condition,
		autoResolveEnabled: r.autoResolveEnabled ?? false,
		autoResolveCondition,
		clientConfig,
		channels: channels.length > 0 ? channels : defaultChannels(),
		allowThroughDnd: r.allowThroughDnd ?? false,
	};
}
